*==============================================================================
* 03_labels_en.do  -  English labels for the columns of the Rahavard Novin
*   export (keyed by the Stata name of each column). Used by 03_build_master.do
*   for the English sheet. Columns without a label here keep their name.
*==============================================================================
cap label variable Symbol "Company (database label)"
cap label variable شرکت "Company code"
cap label variable Year "Fiscal year"
cap label variable کدصنعتجزئی "Industry code (detailed)"
cap label variable کدصنعتکلی "Industry code (general)"
cap label variable صنعت "Industry"
cap label variable طبقه "Industry sub-class"
cap label variable بازار "Market (TSE / Farabourse)"
cap label variable نماد "Ticker"
cap label variable تاریخمصوب "Approval date"
cap label variable نوع "Statement type"
cap label variable تلفیقی "Consolidated statements (yes/no)"
cap label variable حسابرسیشده "Audited (yes/no)"
cap label variable تجدیدارائهشده "Restated (yes/no)"
cap label variable وجوهنقدوموجودیهاینزدبانکه "Cash and bank balances"
cap label variable سرمایهگذاریهایکوتاهمدت "Short-term investments"
cap label variable سرمایهاجارهایحصهجاری "Finance lease receivable, current portion"
cap label variable داراییهایآمادهواگذاری "Assets held for sale"
cap label variable حصهجاریخالصتسهیلاتاعطائی "Loans granted, net, current portion"
cap label variable تسهیلاتاعطاییعقوداسلامی "Loans granted, Islamic contracts"
cap label variable تسهیلاتاعطاییقرضالحسنه "Loans granted, Qard al-Hasan"
cap label variable حسابهاواسناددریافتیتجاری "Trade notes and accounts receivable"
cap label variable سایرحسابهاواسناددریافتیتجا "Other trade receivables"
cap label variable طلبازشرکتهایگروهوشرکتهایو "Receivables from group and associated companies"
cap label variable موجودیمواداولیهوبستهبندی "Inventory: raw materials and packaging"
cap label variable موجودیکالایدرجریانساخت "Inventory: work in progress"
cap label variable موجودیکالایساختهشده "Inventory: finished goods"
cap label variable موجودیقطعاتولوازمیدکی "Inventory: spare parts"
cap label variable موجودیکالایخریداریشده "Inventory: purchased goods"
cap label variable کالایدرراه "Goods in transit"
cap label variable کالایامانیمانزددیگران "Own goods held by others (consignment)"
cap label variable کالایامانیدیگراننزدما "Others' goods held by the company (consignment)"
cap label variable سایرموجودیها "Other inventories"
cap label variable افزایشیاکاهشارزشموجودیها "Inventory valuation adjustment"
cap label variable انبارملزومات "Supplies store"
cap label variable موجودیضایعات "Scrap inventory"
cap label variable دارائیهایمالی "Financial assets"
cap label variable پروژههایدرجریانپیشرفت "Projects in progress"
cap label variable داراییهایزیستیغیرمولدومولد "Biological assets"
cap label variable داراییهایغیرجارینگهداریشده "Non-current assets held for sale"
cap label variable مطالباتازبیمهگذارانونمایندگ "Receivables from policyholders and agents"
cap label variable مطالباتازبیمهگرانوبیمهگران "Receivables from insurers and reinsurers"
cap label variable حسابهاواسناددریافتنی "Notes and accounts receivable"
cap label variable سایرحسابهاواسناددریافتنی "Other notes and accounts receivable"
cap label variable سهمبیمهگراناتکاییازذخائرفن "Reinsurers' share of technical reserves"
cap label variable موجودیموادوکالا "Inventories, total"
cap label variable سفارشاتواعتباراتاسنادی "Orders and letters of credit"
cap label variable سفارشاتموادوکالا "Orders of materials and goods"
cap label variable سفارشاتوپیشپرداختها "Orders and prepayments"
cap label variable وجوهومنابعحاصلازاوراقمشارک "Funds from participation bonds"
cap label variable مطالباتازبانکمرکزی "Claims on the Central Bank"
cap label variable مطالباتازسایربانکهاوموسسات "Claims on other banks and credit institutions"
cap label variable مطالباتازدولت "Claims on the government"
cap label variable تسهیلاتاعطایی "Loans granted"
cap label variable تسهیلاتاعطاییومطالباتازبخش "Loans and receivables, private sector"
cap label variable تسهیلاتاعطاییومطالباتازشرکت "Loans and receivables, companies"
cap label variable تسهیلاتاعطاییومطالباتازسایر "Loans and receivables, other"
cap label variable مطالباتبابتاعتباراتاسنادیوب "Receivables for letters of credit and guarantees"
cap label variable پیشپرداختها "Prepayments"
cap label variable جمعداراییهایجاری "Total current assets"
cap label variable مطالباتبلندمدت "Long-term receivables"
cap label variable سرمایهگذاریهایبلندمدت "Long-term investments"
cap label variable سرمایهاجارهایبلندمدت "Finance lease receivable, long-term portion"
cap label variable حصهبلندمدتخالصتسهیلاتاعطائی "Loans granted, net, long-term portion"
cap label variable اجارههایسرمایهای "Capital leases"
cap label variable وجوهومنابعحاصلازمشارکت "Funds from participations"
cap label variable سرمایهگذاریبلندمدتدرشرکتها "Long-term investments in companies"
cap label variable سایرسرمایهگذاریهایبلندمدت "Other long-term investments"
cap label variable طرحهایتوسعهوتکمیل "Development and completion projects"
cap label variable سفارشاتوپیشپرداختهایسرمایه "Capital orders and prepayments"
cap label variable حسابهاواسناددریافتنیتجاریبل "Long-term trade notes and accounts receivable"
cap label variable اوراقمشارکت "Participation bonds"
cap label variable گواهیسپردهکوتاهمدت "Short-term certificates of deposit"
cap label variable اوراقاجارهپرداختنی "Ijara (lease) bonds payable"
cap label variable سرمایهگذاریهاومشارکتها "Investments and participations"
cap label variable داراییهاینامشهود "Intangible assets"
cap label variable سرقفلی "Goodwill"
cap label variable سایرداراییها "Other assets"
cap label variable سرمایهگذاریهاوسایرداراییها "Investments and other assets"
cap label variable اموالماشینآلاتوتجهیزات "Property, plant and equipment"
cap label variable اقلامدرراه "Items in transit (assets)"
cap label variable ذخیرهاستهلاکداراییها "Accumulated depreciation"
cap label variable خالصداراییهایثابت "Net fixed assets"
cap label variable جمعداراییهایغیرجاری "Total non-current assets"
cap label variable جمعکلداراییها "Total assets"
cap label variable اوراقمشارکتحصهجاری "Participation bonds, current portion"
cap label variable حسابهاواسنادپرداختنیتجاری "Trade notes and accounts payable"
cap label variable سایرحسابهاواسنادپرداختنی "Other notes and accounts payable"
cap label variable بدهیبهشرکتهایگروهوشرکتهای "Payables to group and associated companies"
cap label variable سپردههاوپیشدریافتها "Deposits and advances received"
cap label variable ذخیرهمالیاتبردرآمد "Income tax provision"
cap label variable بدهیبهبانکمرکزی "Due to the Central Bank"
cap label variable بدهیبهسایربانکهاوموسساتاعت "Due to other banks and credit institutions"
cap label variable سپردههایدیداری "Demand deposits"
cap label variable سپردههایقرضالحسنهوپسانداز "Qard al-Hasan and savings deposits"
cap label variable سپردههایسرمایهگذاریمدتدار "Term investment deposits"
cap label variable سایرسپردهها "Other deposits"
cap label variable مالیاتپرداختنی "Taxes payable"
cap label variable سایرذخائر "Other provisions"
cap label variable تسهیلاتجاریمالیدریافتی "Short-term financial facilities (loans)"
cap label variable سودپرداختنیبهسپردهگذاران "Profit payable to depositors"
cap label variable بدهیبانکبابتپذیرشاعتباراتاس "Bank liability for accepted letters of credit"
cap label variable بدهیبهبیمهگذارانونمایندگان "Due to policyholders and agents"
cap label variable بدهیبهبیمهگذاراناتکایی "Due to reinsurers"
cap label variable سپردهاتکاییواگذاری "Reinsurance deposits"
cap label variable بدهیبهبیمهمرکزیایران "Due to Central Insurance of Iran"
cap label variable سودسهامدولت "Government dividends"
cap label variable ذخیرهحقبیمه "Premium reserve"
cap label variable ذخیرهخسارتمعوق "Outstanding claims reserve"
cap label variable ذخیرهریسکهایمنقضینشده "Unexpired risk reserve"
cap label variable سایرذخائرفنی "Other technical reserves"
cap label variable سودسهامپیشنهادیوپرداختنی "Proposed and payable dividends"
cap label variable بدهیهایمرتبطباداراییهایغیر "Liabilities of non-current assets held for sale"
cap label variable جمعبدهیهایجاری "Total current liabilities"
cap label variable حسابهاواسنادپرداختنیبلندمدت "Long-term notes and accounts payable"
cap label variable گواهیسپردهبلندمدت "Long-term certificates of deposit"
cap label variable پیشدریافتهایبلندمدت "Long-term advances received"
cap label variable سپردههایسرمایهگذاریبلندمدت "Long-term investment deposits"
cap label variable تسهیلاتمالیدریافتیبلندمدت "Long-term financial facilities (loans)"
cap label variable حقبیمهسالهایآینده "Premiums of future years"
cap label variable ذخیرهمزایایپایانخدمتکارکنان "Employee end-of-service benefits provision"
cap label variable اقلامدرراهبدهی "Items in transit (liabilities)"
cap label variable سایربدهیها "Other liabilities"
cap label variable جمعبدهیهایغیرجاری "Total non-current liabilities"
cap label variable جمعکلبدهیها "Total liabilities"
cap label variable حقوقعمومی "Public rights"
cap label variable سرمایه "Paid-in capital"
cap label variable سودوزیانانباشته "Retained earnings (accumulated profit or loss)"
cap label variable اندوختهقانونی "Legal reserve"
cap label variable اندوختهطرحوتوسعه "Expansion and development reserve"
cap label variable اندوختهاحتیاطی "Contingency reserve"
cap label variable اندوختهصرفسهام "Share premium reserve"
cap label variable اندوختهمخصوص "Special reserve"
cap label variable مازادزیانانباشتهسهماقلیت "Minority accumulated loss surplus"
cap label variable سایراندوختهها "Other reserves"
cap label variable مازادتجدیدارزیابیداراییهایغ "Revaluation surplus of non-current assets"
cap label variable افزایشسرمایهدرجریان "Capital increase in progress"
cap label variable سودوزیانناشیازتسعیردارائیه "Gain or loss on translation of assets"
cap label variable نتیجهتغییراتناشیازیکسانسازی "Effect of harmonising accounting policies"
cap label variable اندوختهتسعیردارائیهاوبدهیها "Translation reserve"
cap label variable مازادتجدیدارزیابیدارائیهایثا "Revaluation surplus of fixed assets"
cap label variable تفاوتناشیازتسعیرارز "Foreign-exchange translation difference"
cap label variable سهماقلیت "Minority interest"
cap label variable سهمشرکتاصلیدرفرعی "Parent's share in subsidiaries"
cap label variable جمعحقوقصاحبانسهامدرپایانسا "Total shareholders' equity at year end"
cap label variable جمعکلبدهیهاوحقوقصاحبانسها "Total liabilities and shareholders' equity"
cap label variable حقوقعمومیمصوب "Public rights, AGM-approved"
cap label variable سرمایهمصوب "Capital, AGM-approved"
cap label variable سودوزیانانباشتهمصوب "Retained earnings, AGM-approved"
cap label variable اندوختهقانونیمصوب "Legal reserve, AGM-approved"
cap label variable اندوختهسرمایهایمصوب "Capital reserve, AGM-approved"
cap label variable اندوختهاحتیاطیمصوب "Contingency reserve, AGM-approved"
cap label variable اندوختهطرحوتوسعهمصوب "Expansion reserve, AGM-approved"
cap label variable سایراندوختههایمصوب "Other reserves, AGM-approved"
cap label variable افزایشسرمایهدرجریانمصوب "Capital increase in progress, AGM-approved"
cap label variable جمعحقوقصاحبانسهاممصوبدرمج "Total shareholders' equity, AGM-approved"
cap label variable ارزشروز "Market value of equity (rials)"
cap label variable PS "Column PS (probably price-to-sales)"
cap label variable درآمدحقبیمهصادره "Gross premiums written"
cap label variable کاهشافزایشذخایرحقبیمه "Change in premium reserves"
cap label variable درآمدحقبیمه "Premium income"
cap label variable حقبیمهاتکائیواگذاری "Reinsurance premiums ceded"
cap label variable کاهشافزایشذخیرهحقبیمهاتکا "Change in reinsurance premium reserve"
cap label variable هزینهحقبیمهاتکائیواگذاری "Reinsurance premium expense"
cap label variable درآمدحقبیمهسهمنگهداری "Net retained premium income"
cap label variable خسارتپرداختی "Claims paid"
cap label variable افزایشکاهشذخایرخسارت "Change in claims reserves"
cap label variable هزینهخسارت "Claims expense"
cap label variable خسارتدریافتیازبیمهگراناتکائ "Claims recovered from reinsurers"
cap label variable افزایشکاهشذخیرهخسارتمعوقب "Change in outstanding claims reserve, reinsurers"
cap label variable خسارتسهمبیمهگراناتکائی "Reinsurers' share of claims"
cap label variable هزینهخسارتسهمنگهداری "Net retained claims expense"
cap label variable هزینهکارمزدوکارمزدمنافعاتکا "Commission expense (incl. reinsurance profit commission)"
cap label variable درآمدکارمزدوکارمزدمنافعاتکا "Commission income (incl. reinsurance profit commission)"
cap label variable خالصدرآمدهزینهکارمزدوکارم "Net commission income or expense"
cap label variable کاهشافزایشسایرذخایرفنی "Change in other technical reserves"
cap label variable هزینهعوارضشخصثالث "Third-party levy expense"
cap label variable هزینهسهمصندوقتامینخسارتهایب "Compensation-fund contribution expense"
cap label variable هزینهسهموزارتکشور "Ministry of Interior share expense"
cap label variable هزینهسهمناجا "Police (NAJA) share expense"
cap label variable هزینهسهمبهداشت "Health-sector share expense"
cap label variable سایرهزینههایبیمهای "Other insurance expenses"
cap label variable خالصسایردرآمدهاوهزینههایب "Net other insurance income and expenses"
cap label variable درآمدسرمایهگذاریازمحلذخایر "Investment income from reserves"
cap label variable کاهشافزایشذخیرهکاهشارزشسر "Change in investment impairment provision"
cap label variable خالصدرآمدسرمایهگذاریهاازمحل "Net investment income from reserves"
cap label variable سودناخالصفعالیتبیمهای "Gross profit from insurance activities"
cap label variable درآمدسرمایهگذاریازمحلسایرم "Investment income from other sources"
cap label variable هزینههایاداریوعمومیوپرسنلی "Administrative, general and personnel expenses"
cap label variable درآمدحاصلازخدماتوفروش "Revenue from sales and services (operating revenue)"
cap label variable سودحاصلازسرمایهگذاریها "Income from investments"
cap label variable سودحاصلازفروشسرمایهگذاریها "Gain on sale of investments"
cap label variable سودحاصلازسایرفعالیتها "Income from other activities"
cap label variable سودتسهیلاتاعطایی "Interest income on loans granted"
cap label variable درآمدحاصلازعملیاتلیزینگوخد "Leasing and service income"
cap label variable سوداوراقمشارکت "Interest on participation bonds"
cap label variable درآمدحاصلازقراردادهایمشارکت "Income from participation contracts"
cap label variable درآمدحاصلازفروشسرمایهگذاری "Income from sale of investments"
cap label variable سودحاصلازسرمایهگذاریهاوسپر "Income from investments and deposits"
cap label variable جایزهسپردهقانونی "Statutory deposit bonus"
cap label variable سودوجهالتزامدریافتی "Penalty income received"
cap label variable سایردرآمدهایمشاع "Other joint income"
cap label variable فروشخالصدرآمدحاصلازخدمات "Net sales and service revenue"
cap label variable سودعلیالحسابسپردههایسرمایه "Provisional profit on investment deposits"
cap label variable تفاوتسودقطعیوعلیالحسابسپرد "Difference between final and provisional deposit profit"
cap label variable هزینهافزایشنسبتدارائیهایثابت "Expense of fixed-asset ratio increase"
cap label variable سودتسهیلاتاعطاییغیرمشاع "Interest income on loans, non-joint"
cap label variable سوداوراقمشارکتغیرمشاع "Interest on participation bonds, non-joint"
cap label variable درآمدکارمزد "Commission income"
cap label variable درآمداجارهسرمایهای "Capital lease income"
cap label variable درآمدقراردادهایعاملیت "Agency contract income"
cap label variable نتیجهمعاملاتارزی "Foreign-exchange trading result"
cap label variable سودوجهالتزامدریافتیغیرمشاع "Penalty income, non-joint"
cap label variable سایردرآمدهایغیرمشاع "Other non-joint income"
cap label variable حقالوکاله "Agency fee (wakala)"
cap label variable جمعدرآمدها "Total revenue"
cap label variable بهایتمامشدهکالایفروشرفته "Cost of goods sold"
cap label variable بهایتمامشدهاملاکواگذارشدهو "Cost of real estate transferred"
cap label variable هزینهتامینمنابعمالیعملیاتلی "Funding cost of leasing operations"
cap label variable سودناویژه "Gross profit"
cap label variable هزینههایمالیتسهیلاتلیزینگ "Financial expenses of leasing facilities"
cap label variable کارمزدنقلوانتقالسهام "Share transfer fees"
cap label variable هزینههایتوزیعوفروش "Distribution and selling expenses"
cap label variable سودپرداختیبهاستثناءسودسپرد "Interest paid excluding deposit interest"
cap label variable سودپرداختیبهسپردهگذاران "Interest paid to depositors"
cap label variable مازادپرداختیبهسپردهگذاران "Excess paid to depositors"
cap label variable هزینههایعمومیواداری "General and administrative expenses"
cap label variable خالصدرآمدهاوهزینههایعملیاتی "Net other operating income and expenses"
cap label variable درآمدهاوهزینههایاستثنایی "Exceptional income and expenses"
cap label variable برگشتذخیرهکاهشارزشسرمایهگذا "Reversal of investment impairment provision"
cap label variable سودزیانعملیاتی "Operating profit (loss)"
cap label variable سایردرآمدهاوهزینههایغیربیمه "Other non-insurance income and expenses"
cap label variable هزینهمطالباتمشکوکالوصول "Doubtful receivables expense"
cap label variable هزینهاستهلاک "Depreciation expense"
cap label variable کارمزدپرداختیهزینهکارمزد "Commission and fee expense"
cap label variable هزینههایمالی "Financial expenses"
cap label variable سودزیانتسعیرتسهیلاتارزیدر "Translation gain or loss on foreign-currency loans"
cap label variable هزینهکل "Total expenses"
cap label variable درآمدحاصلازسرمایهگذاری "Investment income"
cap label variable اضافهکسرجذبسربار "Over- or under-absorbed overhead"
cap label variable خالصسایردرآمدهاهزینهها "Net other income and expenses"
cap label variable سودزیانفروشدارائیهایزیستیمو "Gain or loss on sale of biological assets"
cap label variable تعدیلارزشسرمایهگذاریها "Investment value adjustment"
cap label variable پاداشهیئتمدیره "Board of directors' bonus"
cap label variable سودسپردههایارزی "Interest on foreign-currency deposits"
cap label variable سایرهزینهها "Other expenses"
cap label variable سایردرآمدهاوهزینههایعملیاتی "Other operating income and expenses"
cap label variable سودوزیانعملیاتی "Operating profit (loss), alternative format"
cap label variable سایردرآمدهاوهزینههایغیرعمل "Other non-operating income and expenses"
cap label variable سهمگروهازسودشرکتهایوابسته "Group share of associates' profit"
cap label variable سودزیانقبلازتحصیلشرکتهای "Profit before acquisition of subsidiaries"
cap label variable اقلامغیرمترقبهاثراتانباشته "Extraordinary items and cumulative effects"
cap label variable سودزیانقبلازکسرمالیات "Profit (loss) before tax"
cap label variable مالیات "Income tax"
cap label variable سهماقلیتازسودسالجاری "Minority share of current-year profit"
cap label variable سودزیانپسازکسرمالیات "Net profit (loss) after tax"
cap label variable سودانباشتهابتدایدوره "Retained earnings at beginning of period"
cap label variable تعدیلاتسنواتی "Prior-period adjustments"
cap label variable سودسهاممصوبمجمعسالقبل "Dividends approved by previous AGM"
cap label variable انتقالازسایراندوختههابهسود "Transfer from other reserves to retained earnings"
cap label variable پاداشهیئتمدیرهمصوبهسالقبل "Board bonus approved for prior year"
cap label variable سایراندوختههایمصوبسالقبل "Other reserves approved for prior year"
cap label variable انتقالازحسابسودوزیانانباشت "Transfer from retained earnings"
cap label variable کاهشافزایشسرمایهازمحلزیان "Capital change from accumulated losses"
cap label variable سودقابلتخصیص "Distributable profit"
cap label variable ذخیرهپاداشهیئتمدیره "Board bonus provision"
cap label variable سودسهاممصوبسالجاری "Dividends approved for current year"
cap label variable خالصسایردرآمدهاوهزینههایع "Net other income and expenses (appropriation)"
cap label variable سودوزیانانباشتهدرپایاندوره "Retained earnings at end of period"
cap label variable نسبتسودبهفروش "Profit-to-sales ratio"
cap label variable EPSناخالص "EPS, gross"
cap label variable EPSخالص "EPS, net"
cap label variable نقدحاصلازعملیات "Cash generated from operations"
cap label variable پرداختهاینقدیبابتمالیاتبرد "Income tax paid"
cap label variable جریانخالصورودخروجنقدحاصل "Net cash flow from operating activities"
cap label variable دریافتهاینقدیحاصلازفروشدار "Proceeds from sale of assets (truncated header)"
cap label variable پرداختهاینقدیبرایخریددارایی "Payments to purchase assets (truncated header)"
cap label variable دریافتهاینقدیحاصلازفروشسرم "Proceeds from sale of investments"
cap label variable دریافتهاینقدیحاصلازفروششرک "Proceeds from sale of subsidiaries"
cap label variable پرداختهاینقدیبرایخریدشرکته "Payments to acquire subsidiaries"
cap label variable پرداختهاینقدیبرایخریدسرمایه "Payments to purchase investments"
cap label variable پرداختهاینقدیبرایتحصیلسرمای "Payments to acquire investments (truncated header)"
cap label variable پرداختهاینقدیبابتتسهیلاتاعط "Payments for loans granted"
cap label variable دریافتهاینقدیحاصلازاسترداد "Proceeds from repayment of loans granted"
cap label variable دریافتهاینقدیحاصلازسودتسهی "Interest received on loans granted"
cap label variable دریافتهاینقدیحاصلازسودسهام "Dividends received"
cap label variable دریافتهاینقدیحاصلازسودسرما "Interest received on investments"
cap label variable دریافتهاینقدیحاصلازسودسایر "Other interest received"
cap label variable سایرجریانهاینقدیحاصلازفعال "Other cash flows from investing activities"
cap label variable جريانخالصورودخروجنقدحاصل "Net cash flow from investing activities"
cap label variable جريانخالصورودخروجنقدقبلا "Net cash flow before financing activities"
cap label variable دریافتهاینقدیحاصلازافزایشس "Proceeds from capital increase"
cap label variable دریافتهاینقدیحاصلازافزايشس "Proceeds from capital increase (second column)"
cap label variable دریافتهاینقدیحاصلازصرفسهام "Proceeds from share premium"
cap label variable دریافتهاینقدیحاصلازفروشسها "Proceeds from sale of treasury shares"
cap label variable پرداختهاینقدیبرایخریدسهامخ "Payments to buy treasury shares"
cap label variable دریافتهاینقدیحاصلازتسهیلات "Proceeds from financial facilities (loans)"
cap label variable پرداختهاینقدیبابتاصلتسهیلات "Repayment of loan principal"
cap label variable پرداختهاینقدیبابتسودتسهیلات "Interest paid on loans"
cap label variable دریافتهاینقدیحاصلازانتشارا "Proceeds from issuing participation bonds"
cap label variable پرداختهاینقدیبابتاصلاوراقم "Repayment of participation bond principal"
cap label variable پرداختهاینقدیبابتسوداوراقم "Interest paid on participation bonds"
cap label variable پرداختهاینقدیبابتاصلاوراقخ "Repayment of bond principal (type truncated)"
cap label variable پرداختهاینقدیبابتسوداوراقخ "Interest paid on bonds (type truncated)"
cap label variable پرداختهاینقدیبابتسودسهامبه "Dividends paid (recipient truncated)"
cap label variable دریافتهاینقدیبابتانتشاراورا "Proceeds from issuing bonds"
cap label variable کاهشافزایشوجوهمسدودیبابتا "Change in restricted deposits"
cap label variable پرداختهاینقدیبابتسوداوراقس "Interest paid on bonds (type truncated, s)"
cap label variable پرداختهاینقدیبابتسوداوراقص "Interest paid on bonds (type truncated, sukuk)"
cap label variable دریافتهاینقدیبابتاستقراض "Proceeds from borrowing"
cap label variable بازپرداختهاینقدیبابتاستقراض "Repayment of borrowing"
cap label variable پرداختهاینقدیبابتاصلاقساطا "Repayment of lease instalment principal"
cap label variable پرداختهاینقدیبابتسوداجارهس "Interest paid on capital leases"
cap label variable پرداختهاینقدیبابتسودسهام "Dividends paid"
cap label variable بازپرداختودایعمشترکین "Repayment of subscriber deposits"
cap label variable دریافتهاینقدیبابتودایعمشترک "Proceeds from subscriber deposits"
cap label variable MT "Column MT (probably net cash flow from financing activities)"
cap label variable خالصافزايشکاهشدرموجودینقد "Net increase (decrease) in cash"
cap label variable ماندهموجودینقددرابتدایدوره "Cash at beginning of period"
cap label variable تعدیلاتتلفیقی "Consolidation adjustments"
cap label variable تاثيرتغييراتنرخارز "Effect of exchange-rate changes on cash"
cap label variable ماندهموجودینقددرپاياندوره "Cash at end of period"
cap label variable معاملاتغیرنقدی "Non-cash transactions"
cap label variable حاشیهسودخالص "Net profit margin (%)"
cap label variable حاشیهسودناخالص "Gross margin (%)"
cap label variable حاشیهسودعملیاتی "Operating profit margin (%)"
cap label variable حاشیهسودناویژه "Gross profit margin (%), alternative"
cap label variable سودبهسودناویژه "Net profit to gross profit (%)"
cap label variable بازدهداراییهاROA "Return on assets, ROA (%)"
cap label variable بازدهسرمایه "Return on capital (%)"
cap label variable بازدهیسرمایهROE "Return on equity, ROE (%)"
cap label variable بازدهسرمایهدرگردش "Return on working capital (%)"
cap label variable بازدهداراییثابت "Return on fixed assets (%)"
cap label variable سنجشسودمندیوام "Loan usefulness ratio"
cap label variable نسبتجاری "Current ratio"
cap label variable نسبتآنی "Quick ratio"
cap label variable نسبتنقدینگی "Cash ratio"
cap label variable نسبتداراییهایجاری "Current assets to total assets"
cap label variable نسبتکفایتنقد "Cash adequacy ratio"
cap label variable نسبتگردشنقد "Cash turnover ratio"
cap label variable سرمایهدرگردشخالص "Net working capital"
cap label variable دورهموجودیموادوکالا "Inventory holding period (days)"
cap label variable دورهوصولمطالبات "Collection period (days)"
cap label variable نسبتکالابهسرمایهدرگردش "Inventory to working capital"
cap label variable گردشسرمایهجاری "Working capital turnover"
cap label variable گردشداراییهایثابت "Fixed asset turnover"
cap label variable گردشمجموعداراییها "Total asset turnover"
cap label variable نسبتبدهی "Debt ratio"
cap label variable نسبتبدهیبهارزشویژه "Debt to equity"
cap label variable نسبتداراییثابتبهارزشویژه "Fixed assets to equity"
cap label variable نسبتبدهیبلندمدتبهارزشویژه "Long-term debt to equity"
cap label variable نسبتبدهیجاریبهارزشویژه "Current debt to equity"
cap label variable نسبتمالکانه "Equity ratio (%)"
cap label variable نسبتپوششبدهی "Debt coverage ratio"
cap label variable نسبتپوششبهره "Interest coverage ratio"
cap label variable نسبتبارمالیوام "Financial burden ratio"
cap label variable هزینههایمالیبهسودخالص "Financial expenses to net profit (%)"
cap label variable هزینههایمالیبهسودعملیاتی "Financial expenses to operating profit (%)"
cap label variable حقتقدم "Rights issue (%)"
cap label variable سهامجایزه "Bonus shares (%)"
cap label variable DPS "Dividend per share (DPS)"
cap label variable قیمتپایه "Base price"
cap label variable قیمتپایانی "Closing price at year end"
cap label variable بازدهی "Annual return (%)"
cap label variable رتبهنقدشوندگی "Liquidity rank"
cap label variable PD "Column PD (price block 2: rights issue)"
cap label variable PE "Column PE (price block 2: bonus shares)"
cap label variable PF "Column PF (price block 2: DPS)"
cap label variable PG "Column PG (price block 2: base price)"
cap label variable PH "Column PH (price block 2: closing price)"
cap label variable PI "Column PI (price block 2: return)"
cap label variable PJ "Column PJ (price block 2: liquidity rank)"
