*==============================================================================
* 70_report.do  -  collects ALL results into one Word file:
*                  $OUT/Results_Report.docx  (built-in putdocx, Stata 15+)
*   1 Data: winsorization, sample, descriptives, correlations, life cycle, DEA
*   2 Assumption and specification tests
*   3 Hypothesis decisions
*   4 One table per hypothesis (GMM next to static FE) + reverse causality
*   5 Simple slopes and economic magnitude
*   6 Robustness, sensitivity, identification
*   7 First-stage models, within-stage estimates
*   8 All figures
*==============================================================================

*------------------------------------------------------------------------------
* helpers
*------------------------------------------------------------------------------
global TBL = 0

cap program drop doc_h
program define doc_h
    args level text
    putdocx paragraph, style(Heading`level')
    putdocx text ("`text'")
end

cap program drop doc_p
program define doc_p
    args text
    putdocx paragraph
    putdocx text ("`text'"), font("Times New Roman", 9) italic
end

* matrix -> Word table
cap program drop doc_mat
program define doc_mat
    args M fmt
    if "`fmt'" == "" local fmt "%9.4f"
    global TBL = $TBL + 1
    putdocx table t$TBL = matrix(`M'), rownames colnames nformat(`fmt') ///
        font("Times New Roman", 8) border(all, single)
end

* data in memory -> Word table
cap program drop doc_data
program define doc_data
    syntax [varlist]
    if "`varlist'" == "" unab varlist : _all
    foreach v of local varlist {
        cap confirm numeric variable `v'
        if !_rc format `v' %10.4f
    }
    global TBL = $TBL + 1
    putdocx table t$TBL = data(`varlist'), varnames font("Times New Roman", 8) border(all, single)
end

* sheet of Tables.xlsx -> Word table
cap program drop doc_sheet
program define doc_sheet
    syntax , SHEET(string) [CELLRANGE(string) NOFIRSTROW]
    preserve
    local fr = cond("`nofirstrow'" == "", "firstrow", "")
    local cr = cond("`cellrange'" == "", "", "cellrange(`cellrange')")
    cap import excel using "$OUT/Tables.xlsx", sheet("`sheet'") `fr' `cr' clear
    if _rc | _N == 0 {
        restore
        doc_p "(sheet `sheet' not available)"
        exit
    }
    doc_data
    restore
end

* coefficient matrix (b, se, p) for a stored estimate and a coefficient list
cap program drop coefmat
program define coefmat
    args est M coefs
    cap qui est restore `est'
    if _rc {
        qui estimates use "$OUT/est_`est'"
        qui est store `est'
    }
    local k : word count `coefs'
    matrix `M' = J(`k', 3, .)
    local rn ""
    local i = 0
    foreach c of local coefs {
        local ++i
        local cc = subinstr("`c'", ".", "_", .)
        local rn "`rn' `cc'"
        cap local b = _b[`c']
        if _rc continue
        local se = _se[`c']
        if `se' == 0 | missing(`se') continue
        local df = e(df_r)
        if missing(`df') local df = e(N_g) - 1
        if missing(`df') local df = e(N_clust) - 1
        matrix `M'[`i', 1] = `b'
        matrix `M'[`i', 2] = `se'
        matrix `M'[`i', 3] = cond(missing(`df'), 2 * normal(-abs(`b' / `se')), ///
            2 * ttail(`df', abs(`b' / `se')))
    }
    matrix rownames `M' = `rn'
    matrix colnames `M' = b se p
end

*------------------------------------------------------------------------------
putdocx clear
putdocx begin, landscape font("Times New Roman", 10)
putdocx paragraph, style(Title)
putdocx text ("Empirical Results")
putdocx paragraph
putdocx text ("The Asymmetric Impact of Managerial Ability on Investment Efficiency under Capital Structure Deviation: Evidence from Emerging Markets"), italic
putdocx paragraph
putdocx text ("Generated by 70_report.do on `c(current_date)' `c(current_time)'. Two-step System GMM; p-values of hypotheses are one-sided in the predicted direction.")

*==============================================================================
* 1. DATA
*==============================================================================
doc_h 1 "1. Data and descriptive statistics"

doc_h 2 "Table 0. Winsorization at the 1st and 99th percentiles"
preserve
    use "$OUT/log_winsorization.dta", clear
    keep if tag == "main"
    gen double pct_changed = 100 * (n_low + n_high) / N
    drop tag
    doc_data
restore

use "$OUT/analysis_panel.dta", clear
xtset FirmID Year

doc_h 2 "Table 1. Descriptive statistics (estimation sample)"
qui tabstat InvEff Invest SalesGrowth TDA TDAhat CSDev CSDP CSDN FE MA ///
    L_LTA L_MTB L_PROFIT L_FCF IOB COL INDLEV INF Age if EST, ///
    stat(n mean sd min p25 p50 p75 max skewness kurtosis) save
matrix D = r(StatTotal)'
doc_mat D "%9.3f"

doc_h 2 "Table 1b. Direction of investment and leverage deviations (counts)"
gen byte OVERINV = InvEff > 0 if !missing(InvEff)
qui tab OVERINV OVERLEV if EST, matcell(DIR)
cap matrix rownames DIR = Under-investment Over-investment
cap matrix colnames DIR = Under-leveraged Over-leveraged
doc_mat DIR "%9.0f"

doc_h 2 "Table 2. Correlations: Pearson (lower) and Spearman (upper triangle)"
local CV "InvEff CSDP CSDN MA L_LTA L_MTB L_PROFIT L_FCF GROW MAT DEC"
qui corr `CV' if EST
matrix P = r(C)
local n = r(N)
qui spearman `CV' if EST, stats(rho)
matrix S = r(Rho)
local k : word count `CV'
matrix C = P
forvalues i = 1/`k' {
    forvalues j = 1/`k' {
        if `j' > `i' matrix C[`i', `j'] = S[`i', `j']
    }
}
doc_mat C "%6.3f"
local crit = invttail(`n' - 2, 0.025)
local rcrit = `crit' / sqrt(`n' - 2 + `crit'^2)
doc_p "N = `n'. Correlations with |r| > `: di %5.3f `rcrit'' are significant at 5%. Stars are reported in Tables.xlsx, sheet T3_correlations."

doc_h 2 "Table 3. Life-cycle stages"
qui tab LC5 if Year >= 1393, matcell(F5)
cap matrix rownames F5 = Introduction Growth Mature Shake-out Decline
cap matrix colnames F5 = Firm-years
doc_mat F5 "%9.0f"
qui tab STAGE_L OVERLEV if EST, matcell(SC)
cap matrix rownames SC = Growth Maturity Decline
cap matrix colnames SC = Under-leveraged Over-leveraged
doc_p "Stage at t-1 by leverage direction (cells identifying the interaction terms):"
doc_mat SC "%9.0f"
qui tab STAGE_L STAGE if Year >= 1394, matcell(TR)
cap matrix rownames TR = Growth_t1 Maturity_t1 Decline_t1
cap matrix colnames TR = Growth_t Maturity_t Decline_t
doc_p "Stage transitions (counts):"
doc_mat TR "%9.0f"

doc_h 2 "Table 4. Data envelopment analysis (stage 1 of managerial ability)"
doc_sheet, sheet("OA2b_DEA") nofirstrow
doc_h 2 "Sample by year and industry"
doc_sheet, sheet("OA1_sample") nofirstrow

*==============================================================================
* 2. ASSUMPTIONS
*==============================================================================
doc_h 1 "2. Multicollinearity, classical assumptions and specification tests"
doc_h 2 "Table 5. Variance inflation factors (static main-effects model)"
doc_sheet, sheet("T4_VIF") nofirstrow
doc_h 2 "Table 6. Specification and assumption tests (static benchmark of Eq. 6)"
doc_sheet, sheet("T4b_assumptions")

*==============================================================================
* 3. HYPOTHESIS DECISIONS
*==============================================================================
doc_h 1 "3. Hypothesis tests: summary of decisions"
preserve
    cap use "$OUT/T5_hypothesis_summary.dta", clear
    if !_rc doc_data
restore
doc_p "Decisions use one-sided p-values in the predicted direction. A decision is valid only if AR(2) p > 0.10 and Hansen p > 0.10 for that model."

*==============================================================================
* 4. ONE TABLE PER HYPOTHESIS
*==============================================================================
* (estimates come from memory, or from $OUT/est_*.ster saved by 40_main_models.do)
doc_h 1 "4. Results by hypothesis: two-step System GMM and static FE benchmark"
local T6a "H1a: over-leverage (CSD+) and investment inefficiency, Eq. (6a)"
local T6b "H1b: under-leverage (CSD-) and investment inefficiency, Eq. (6b)"
local T6  "Asymmetry of the two effects, Eq. (6)"
local T7  "H2a: over-leverage x life cycle (reference = maturity), Eq. (7)"
local T8  "H2b: under-leverage x maturity (reference = growth/decline), Eq. (8)"
local T9  "H3a: over-leverage x managerial ability, Eq. (9)"
local T10 "H3a: over-leverage x managerial ability x growth/decline, Eq. (10)"
local T11 "H3b: under-leverage x managerial ability, Eq. (11)"
local T12 "H3b: under-leverage x managerial ability x maturity, Eq. (12)"
local H6a "p_H1a"
local H6b "p_H1b"
local H6  "p_asym"
local H7  "p_H2aG p_H2aD p_joint"
local H8  "p_H2b"
local H9  "p_H3a"
local H10 "p_H3aM p_H3aGD p_H3a3"
local H11 "p_H3b"
local H12 "p_H3bGD p_H3bM p_H3b3"
local q = 0
foreach m of global MODELS {
    local ++q
    cap est restore G`m'
    if _rc {
        cap estimates use "$OUT/est_G`m'"
        if _rc continue
        est store G`m'
    }
    doc_h 2 "Table 7.`q'. `T`m''"
    local coefs "L.InvEff ${E`m'} ${P`m'} $XCTRL"
    coefmat G`m' A "`coefs'"
    coefmat S`m' B "`coefs'"
    matrix colnames A = GMM_b GMM_se GMM_p
    matrix colnames B = FE_b FE_se FE_p
    matrix R = A, B
    doc_mat R "%9.4f"
    * diagnostics and hypothesis p-values
    qui est restore G`m'
    local stats "N N_g j ar1p ar2p hansenp dhansenp `H`m''"
    local ns : word count `stats'
    matrix Z = J(`ns', 1, .)
    local i = 0
    foreach s of local stats {
        local ++i
        cap matrix Z[`i', 1] = e(`s')
    }
    matrix rownames Z = `stats'
    matrix colnames Z = GMM
    doc_p "Model diagnostics (N = observations, N_g = firms, j = instruments) and hypothesis p-values:"
    doc_mat Z "%9.4f"
}

doc_h 2 "Reverse causality, Eq. (13): dependent variable CSDev"
cap est restore G13
if _rc {
    cap estimates use "$OUT/est_G13"
    if !_rc est store G13
}
cap est restore G13
if !_rc {
    coefmat G13 A "L.CSDev L.InvEff $XCTRL"
    doc_mat A "%9.4f"
    local stats "N N_g j ar1p ar2p hansenp dhansenp p_theta"
    local ns : word count `stats'
    matrix Z = J(`ns', 1, .)
    local i = 0
    foreach s of local stats {
        local ++i
        cap matrix Z[`i', 1] = e(`s')
    }
    matrix rownames Z = `stats'
    doc_mat Z "%9.4f"
}

*==============================================================================
* 5. ECONOMIC MAGNITUDE
*==============================================================================
doc_h 1 "5. Simple slopes and economic magnitude"
preserve
    cap use "$OUT/T6_economic.dta", clear
    if !_rc doc_data
restore
doc_p "effect_1sd: change in InvEff for a one-standard-deviation increase in CSD+ or CSD-; pct: in percent of the mean absolute InvEff. Low/high MA = mean -/+ 1 SD."

*==============================================================================
* 6. ROBUSTNESS, SENSITIVITY, IDENTIFICATION
*==============================================================================
doc_h 1 "6. Robustness, sensitivity and identification"
doc_h 2 "Robustness R1-R10: key coefficients (se); * p<0.10 ** p<0.05 *** p<0.01"
doc_sheet, sheet("T7_robustness")
doc_h 2 "Sensitivity S1-S6: key coefficients (se)"
doc_sheet, sheet("T8_sensitivity")
doc_h 2 "Sensitivity S7: leave one industry out (Eqs. 6a and 6b)"
doc_sheet, sheet("T8b_leave_industry_out")
doc_h 2 "Oster (2019) bounds and placebo test"
doc_sheet, sheet("T9_identification") nofirstrow
doc_h 2 "Bootstrap of the full procedure (if run)"
doc_sheet, sheet("T9b_bootstrap")

*==============================================================================
* 7. FIRST STAGES AND WITHIN-STAGE ESTIMATES
*==============================================================================
doc_h 1 "7. First-stage models and within-stage estimates"
doc_h 2 "Target leverage model, Eq. (2)"
cap {
    coefmat TGT_main A "L_IOB L_COL L_LTA L_MTB L_PROFIT L_INDLEV L_INF _cons"
    doc_mat A "%9.4f"
}
doc_h 2 "Tobit model of DEA efficiency, Eq. (5)"
cap {
    coefmat TOB_main A "LTA MktShare FCFpos lnAge _cons"
    doc_mat A "%9.4f"
}
doc_h 2 "Within-stage estimates (static FE; descriptive only)"
foreach s in 1 2 3 {
    local sn = cond(`s' == 1, "Growth", cond(`s' == 2, "Maturity", "Decline"))
    cap {
        coefmat W6_`s' A "CSDP CSDN $XCTRL"
        coefmat W9_`s' B "CSDP CSDN MA CSDP_MA $XCTRL"
        coefmat W11_`s' C2 "CSDP CSDN MA CSDN_MA $XCTRL"
        doc_p "`sn' stage (t-1): Eq. (6)"
        doc_mat A "%9.4f"
        doc_p "`sn' stage (t-1): Eq. (9)"
        doc_mat B "%9.4f"
        doc_p "`sn' stage (t-1): Eq. (11)"
        doc_mat C2 "%9.4f"
    }
}

*==============================================================================
* 8. FIGURES
*==============================================================================
putdocx pagebreak
doc_h 1 "8. Figures"
local figs : dir "$OUT" files "Fig*.png"
local figs : list sort figs
foreach f of local figs {
    putdocx paragraph, halign(center)
    putdocx image "$OUT/`f'", width(8)
    doc_p "`f'"
}

putdocx save "$OUT/Results_Report.docx", replace
di as res _n "Word report saved: $OUT/Results_Report.docx"
