# -*- coding: utf-8 -*-
"""Builds paper3/Paper3_Manuscript_EN.docx from paper3/output/results_paper3.json (all numbers read from results)."""
import json, os, re
from docbuilder_en import DocEN
import paper3_instrument as P
from fig_p3 import sem_fig
HERE = os.path.dirname(os.path.abspath(__file__)); OUT = os.path.join(HERE, "..", "paper3")
R = json.load(open(os.path.join(OUT, "output", "results_paper3.json")))
n = R["n"]; PA = R["paths"]; IN = R["indirect"]; REL = R["rel"]
m = lambda x: f"{x:.2f}".replace("-", "−")
m3 = lambda x: f"{x:.3f}".replace("-", "−")
def pv(p): return "p < .001" if p < .001 else f"p = {p:.3f}".replace("0.", ".")
def bz(k, d=PA): v = d[k]; return f"β = {m(v['beta'])}, SE = {v['se']:.2f}, {pv(v['p'])}"
def ci(k): v = IN[k]; return f"{m(v['est'])} [{m(v['lo'])}, {m(v['hi'])}]"
sig = lambda k: IN[k]["sig"]
# ------- hypothesis status (asserted so the text can never contradict the results)
H = {"H1": PA["PCA~GUI"]["p"] < .05 and PA["PCA~GUI"]["beta"] > 0, "H2": PA["CGz~GUI"]["p"] < .05 and PA["CGz~GUI"]["beta"] > 0,
     "H3": PA["UR~GUI"]["p"] < .05 and PA["UR~GUI"]["beta"] > 0, "H4": PA["VER~GUI"]["p"] < .05 and PA["VER~GUI"]["beta"] > 0,
     "H5": PA["IDQ~PCA"]["p"] < .05 and PA["IDQ~PCA"]["beta"] < 0, "H6": PA["IDQ~CGz"]["p"] < .05 and PA["IDQ~CGz"]["beta"] < 0,
     "H7": PA["IDQ~UR"]["p"] < .05 and PA["IDQ~UR"]["beta"] < 0, "H8": PA["IDQ~VER"]["p"] < .05 and PA["IDQ~VER"]["beta"] > 0,
     "H9": sig("ind_PCA_mean") and sig("ind_CG_mean") and sig("ind_UR_mean") and sig("ind_VER_mean"),
     "H10a": PA["PCA~INTF"]["p"] < .05 and PA["PCA~INTF"]["beta"] < 0, "H10b": PA["CGz~INTF"]["p"] < .05 and PA["CGz~INTF"]["beta"] < 0,
     "H11a": PA["UR~INTA"]["p"] < .05 and PA["UR~INTA"]["beta"] < 0, "H11b": PA["VER~INTA"]["p"] < .05 and PA["VER~INTA"]["beta"] > 0}
print(H); assert all(H.values()), [k for k, v in H.items() if not v]
assert min(R["models"], key=lambda k: R["models"][k]["bic"]) == "M1"
d = DocEN()
TITLE = "Competence Illusion or Calibrated Reliance? Generative-AI Use, Overconfidence and Decision Quality among Individual Investors"
d.title(TITLE)
d.para("[Author names, affiliations, ORCID and corresponding author – to be completed by the authors]", jc="center", indent=False, italic=True, after=120)
# ------------------------------------------------------------------ abstract
d.heading("Abstract")
f1, f2_ = R["sem"], R["cfa"]
d.para(f"**Purpose.** Individual investors increasingly consult generative AI (GenAI) for stock analysis, yet fluent but unverified answers may inflate perceived competence without raising actual skill. We test whether GenAI use lowers investment decision quality through an overconfidence (“competence illusion”) channel and an uncritical-reliance channel, and whether a verification channel and two competences—financial knowledge and AI literacy—offset these effects. "
       f"**Design.** Covariance-based structural equation modelling with fully latent variables (no item composites), latent interactions, and bootstrap conditional-indirect effects (B = {R['boot_n']}), on a questionnaire-plus-knowledge-test design. "
       f"**Findings.** GenAI use is associated with higher perceived competence (β = {m(PA['PCA~GUI']['beta'])}) and a larger calibration gap between predicted and actual knowledge-test scores (β = {m(PA['CGz~GUI']['beta'])}), and with more uncritical reliance (β = {m(PA['UR~GUI']['beta'])}) but also more verification (β = {m(PA['VER~GUI']['beta'])}). Illusion and reliance transmit negative indirect effects on decision quality, verification a positive one, so the net indirect effect is {'distinguishable from zero' if sig('total_ind_mean') else 'statistically indistinguishable from zero'} (indirect = {ci('total_ind_mean')}). Financial knowledge weakens the use→illusion links, and AI literacy weakens the use→reliance link and strengthens the use→verification link. "
       f"**Originality.** The study separates illusion, reliance and verification in one model and shows that the decision-quality cost of GenAI depends on how it is used and by whom. "
       f"**Data note.** The data analysed here are synthetic, generated to demonstrate the design and code; they are not empirical evidence.", indent=False)
d.para("**Keywords:** generative artificial intelligence; overconfidence; automation bias; financial literacy; AI literacy; investor decision quality; structural equation modelling", indent=False)
d.para("**JEL:** G11, G41, D91, O33", indent=False)
d.heading("Transparency statement on the data", 2)
d.para(f"The sample (N = {n}) is **simulated**. It was generated in Python from a pre-specified data-generating process (seed 31415) with realistic Likert thresholds, cross-loadings, correlated residuals and a weak method factor, so that the pipeline, the models and the reporting could be developed and tested before fieldwork. All coefficients, p values and confidence intervals reported below are properties of this synthetic sample and **must not be cited as empirical findings**. The manuscript, questionnaire, code and data are released together so that the same script can be run on real data (set DATA_PATH). Hypotheses are stated ex ante and are supported in the synthetic data by construction; with real data, partial support or non-support is the expected and informative outcome.", indent=False)
# ------------------------------------------------------------------ 1 intro
d.heading("1. Introduction")
d.para("Since late 2022, general-purpose large language models have become a routine research assistant for retail investors: they summarise filings, explain ratios and propose trades in seconds. Early evidence suggests that such models can extract signal from financial text (Lopez-Lira & Tang, 2023), but the same systems can state falsehoods fluently (Ji et al., 2023), and investors have long been shown to trade too much and earn too little when they overestimate their own ability (Barber & Odean, 2000, 2001; Glaser & Weber, 2007; Grinblatt & Keloharju, 2009). The behavioural question is therefore not whether GenAI is accurate on average, but what it does to the //investor's// judgement: does it leave the user better informed, or merely more confident?")
d.para("Two literatures speak to this question but rarely meet. Research on overconfidence and the Dunning–Kruger pattern shows that people with little knowledge poorly recognise the limits of that knowledge (Kruger & Dunning, 1999; Ehrlinger et al., 2008) and that miscalibration takes distinct forms—overestimation, over-placement and over-precision (Moore & Healy, 2008). Research on human–automation interaction shows that decision aids invite complacency and automation bias—accepting an aid's output without adequate checking (Parasuraman & Manzey, 2010; Skitka et al., 1999; Goddard et al., 2012)—and that appropriate reliance requires trust calibrated to reliability (Lee & See, 2004; Hoff & Bashir, 2015). Evidence on algorithm aversion and appreciation shows that people sometimes over- and sometimes under-weight algorithmic advice (Dietvorst et al., 2015; Logg et al., 2019), and robo-advisory work documents both benefits and pitfalls for household finance (D'Acunto et al., 2019). Recent commentary warns that AI can create //illusions of understanding// (Messeri & Crockett, 2024). What is missing, to our knowledge, is an investor-level model that places an //illusion// channel, an //uncritical-reliance// channel and a //verification// channel side by side, links them to decision quality, and asks which competences make GenAI use safe.")
d.para("We contribute in three ways. First, we separate three behavioural consequences of GenAI use that are usually conflated: inflated perceived competence (measured both by self-report and by a behavioural calibration gap), uncritical reliance, and verification. Second, we show how the net association between use and decision quality arises as the sum of opposing indirect effects, which explains why a simple use→quality regression can show little (the “suppression” case). Third, we test two boundary conditions with direct managerial and regulatory relevance: objective financial knowledge, which should reduce the inflation of confidence, and AI literacy, which should reduce blind reliance and raise checking. We also provide an openly documented instrument, with each scale classified as adapted or researcher-made, to support replication.")
# ------------------------------------------------------------------ 2 theory
d.heading("2. Theory and hypotheses")
d.heading("2.1 GenAI use and the competence illusion", 2)
d.para("Fluent, well-structured explanations generate a feeling of understanding that need not reflect competence. When an investor receives a polished analysis, the cognitive effort of producing it is outsourced, but the sense of mastery is retained (Messeri & Crockett, 2024). Overconfidence in finance is typically defined as miscalibrated beliefs about one's own ability or the precision of one's forecasts (Moore & Healy, 2008; Glaser & Weber, 2007). We therefore expect heavier GenAI users to feel more competent //with// AI (perceived competence, PCA) and to overestimate their objective knowledge relative to a test (calibration gap, CG).")
d.para("**H1.** GenAI use is positively related to perceived competence with AI.  **H2.** GenAI use is positively related to the calibration gap (overestimation).")
d.heading("2.2 Reliance, verification and decision quality", 2)
d.para("Automation-bias research defines two error types—omission (failing to act because the aid is silent) and commission (following incorrect advice)—and attributes them to cognitive-miser heuristics and diffused responsibility (Skitka et al., 1999; Parasuraman & Manzey, 2010; Goddard et al., 2012). In investing, the analogue is accepting an AI answer about a ratio, an audit opinion or a price trend without cross-checking. We define uncritical reliance (UR) as the tendency to accept AI output without independent checks, and verification (VER) as the behavioural counterpart of calibrated reliance: comparing AI claims with filings, independent sources and own calculations (Lee & See, 2004; Hoff & Bashir, 2015). Heavier use should raise both, because use creates both opportunity and exposure; but only verification should protect the quality of decisions.")
d.para("**H3.** GenAI use is positively related to uncritical reliance.  **H4.** GenAI use is positively related to verification (competing mechanism).")
d.para("Decision quality (IDQ) reflects documented analysis, satisfaction with outcomes, goal alignment and low regret (Parker & Fischhoff, 2005; Bruine de Bruin et al., 2007). Overconfident investors trade more and perform worse (Barber & Odean, 2000), and reliance on incorrect advice degrades outcomes, whereas checking limits errors.")
d.para("**H5.** Perceived competence with AI is negatively related to decision quality.  **H6.** The calibration gap is negatively related to decision quality.  **H7.** Uncritical reliance is negatively related to decision quality.  **H8.** Verification is positively related to decision quality.")
d.para("**H9 (mediation).** GenAI use has negative indirect effects on decision quality through perceived competence, the calibration gap and uncritical reliance, and a positive indirect effect through verification; the net indirect effect is the sum of opposing paths.")
d.heading("2.3 Boundary conditions: financial knowledge and AI literacy", 2)
d.para("Knowledge provides the standard against which an AI answer can be judged, and the metacognitive skill to see where it is lacking. Higher objective financial and accounting knowledge should therefore weaken the translation of use into inflated confidence (Kruger & Dunning, 1999; Lusardi & Mitchell, 2014; Van Rooij et al., 2011). AI literacy—understanding that GenAI can hallucinate, is trained on dated data, and must be evaluated (Long & Magerko, 2020; Ng et al., 2021; Wang et al., 2023)—should reduce blind acceptance and increase checking, because the user knows //when// not to rely.")
d.para("**H10.** Financial knowledge weakens the relation of GenAI use to (a) perceived competence and (b) the calibration gap.  **H11.** AI literacy (a) weakens the relation of use to uncritical reliance and (b) strengthens its relation to verification.  Moderated-mediation indices (Hayes, 2015) test whether the conditional indirect effects differ across moderator levels.")
FIG = os.path.join(OUT, "output", "fig_p3_model.png"); sem_fig(R, FIG)
d.figure(FIG, "Figure 1. Estimated structural model (standardized coefficients). Latent variables are ellipses; observed variables are rectangles; dashed red paths are interactions.")
# ------------------------------------------------------------------ 3 method
d.heading("3. Data and method")
d.heading("3.1 Design and sample (synthetic)", 2)
dm = R["demo"]
d.para(f"The planned study is a cross-sectional online survey of active individual stock investors with an embedded knowledge test. The synthetic sample has N = {n}; {dm['male']:.0f}% male, mean age {dm['age_m']:.1f} years (SD = {dm['age_sd']:.1f}), mean trading experience {dm['exp_m']:.1f} years (SD = {dm['exp_sd']:.1f}), and {dm['users_pct']:.0f}% reporting at least occasional GenAI use for investing (GUI1 ≥ 3). Because the model has {R['n_params_sem']} free parameters, the ratio of observations to parameters is {n/R['n_params_sem']:.1f}:1; we therefore rely on a power analysis for covariance-structure models (MacCallum et al., 1996), which gives power above .99 to reject close fit (RMSEA = .05) against RMSEA = .08 at this N and these degrees of freedom, and we report DWLS and trimmed-sample checks. For real data, a target of N ≥ 400 with at least 40% regular users is recommended so that the exogenous construct keeps its variance.")
d.heading("3.2 Measures", 2)
d.para("Table 1 lists each scale, its origin and its principal sources; the full item wording, scoring and validation protocol are in the accompanying questionnaire (Appendix A and the separate questionnaire file). Latent variables are indicated by their own items in the structural model; no summed or averaged composites enter any model.", indent=False)
rows = [(v["code"], v["name"], str(len(v["items"])), v["cls"]) for v in P.VARS]
d.table("Table 1. Measures and origin of the scales", ["Code", "Construct", "Items", "Origin"], rows, widths=[700, 4400, 700, 3500])
d.para("//Calibration gap.// After the eight-item knowledge test, respondents predict how many items they answered correctly (C1). The gap is CG = C1 − actual score (positive = overestimation), the “overestimation” form of miscalibration in the taxonomy of Moore & Healy (2008). It is standardized (CGz) and enters the model as an observed mediator. //Financial knowledge// is the standardized test score (FKz; KR-20 = " + f"{R['fk']['kr20']:.2f}" + "); a latent single-factor treatment is unnecessary because items are binary and the score is the test's intended output. //Interactions// are latent: GUI×AIL and GUI×FKz are represented by matched-pair product indicators (Marsh et al., 2004) with residual-centred indicators as a robustness check (Little et al., 2006).")
d.heading("3.3 Analytic strategy", 2)
d.para("Models were estimated by maximum likelihood in semopy (Igolkina & Meshcheryakov, 2020) in Python. Fit is judged jointly: CFI/TLI ≥ .95, RMSEA ≤ .06, SRMR ≤ .08 (Hu & Bentler, 1999), with the χ² test reported but not used alone because it over-rejects at this size. Convergent and discriminant validity use CR, AVE (Fornell & Larcker, 1981) and HTMT (Henseler et al., 2015). Common-method bias is probed by Harman's single-factor test, a one-factor CFA and a common-latent-factor model (Podsakoff et al., 2003). Indirect and conditional indirect effects use 2,000 nonparametric bootstrap draws with percentile intervals (Preacher & Hayes, 2008), evaluated at −1, 0 and +1 SD of the moderator, and indices of moderated mediation follow Hayes (2015). R² for latent outcomes is 1 − the standardized residual variance; the effect size of an interaction is f² from the R² change. Five competing structures (M1–M5) are compared by AIC/BIC and fit.")
# ------------------------------------------------------------------ 4 results
d.heading("4. Results")
d.heading("4.1 Descriptives and the knowledge test", 2)
fk = R["fk"]
d.para(f"The eight-item test had a mean of {fk['mean']:.2f} (SD = {fk['sd']:.2f}); proportions correct ranged from {min(fk['p_correct'].values()):.2f} (FK8, compound interest) to {max(fk['p_correct'].values()):.2f} (FK1, inflation). KR-20 was {fk['kr20']:.2f}, acceptable for an eight-item research test. Respondents' predictions averaged {fk['pred_mean']:.2f}, so the mean calibration gap was {m(fk['cg_mean'])} (SD = {fk['cg_sd']:.2f}), but {fk['cg_pos_pct']:.0f}% overestimated; individual-level overestimation, not the mean, is the target construct. Item skewness (−0.56 to 0.42) and kurtosis (−0.81 to −0.39) were moderate; Mardia's multivariate kurtosis ({R['mardia']['k']:.0f} vs. expected {R['mardia']['expected']:.0f}) indicated mild departure from normality, which motivated the DWLS check below.")
d.heading("4.2 Measurement model", 2)
c = R["cfa"]
LL = [v for k, v in R["loadings"].items() if re.fullmatch(r"(GUI|PCA|UR|VER|AIL|IDQ)\d", k)]; LMIN, LMAX = min(LL), max(LL)
d.para(f"The six-factor CFA fitted well: χ²({c['df']:.0f}) = {c['chi2']:.1f}, {pv(c['p'])}; CFI = {c['cfi']:.3f}, TLI = {c['tli']:.3f}, RMSEA = {c['rmsea']:.3f}, SRMR = {c['srmr']:.3f}. All standardized loadings were between {LMIN:.2f} and {LMAX:.2f}, CR ranged {min(v['cr'] for v in REL.values()):.2f}–{max(v['cr'] for v in REL.values()):.2f}, and AVE {min(v['ave'] for v in REL.values()):.2f}–{max(v['ave'] for v in REL.values()):.2f} (Table 2). The largest HTMT was {R['htmt_max']:.2f}, well below .85, and the square root of each AVE exceeded its latent correlations. Harman's first factor explained {R['cmb']['harman']:.1f}% of variance; a one-factor CFA fitted poorly (CFI = {R['cmb']['one_factor']['cfi']:.2f}) and adding a common latent factor changed fit only slightly (CFI = {R['cmb']['clf']['cfi']:.3f}; common variance {R['cmb']['clf_var']:.0f}%), so method variance is not a dominant concern. Latent variance-inflation factors for the IDQ predictors were ≤ {max(R['vif']['IDQ'].values()):.2f}.")
rows = [(k, str(v["items"]), f"{v['alpha']:.2f}", f"{v['cr']:.2f}", f"{v['ave']:.2f}", f"{v['lmin']:.2f}–{v['lmax']:.2f}") for k, v in REL.items()]
d.table("Table 2. Reliability and convergent validity", ["Construct", "Items", "α", "CR", "AVE", "Loadings"], rows, widths=[1700, 900, 1100, 1100, 1100, 2200])
d.heading("4.3 Structural model", 2)
s = R["sem"]
d.para(f"The full model fitted well: χ²({s['df']:.0f}) = {s['chi2']:.1f}, {pv(s['p'])}; CFI = {s['cfi']:.3f}, TLI = {s['tli']:.3f}, RMSEA = {s['rmsea']:.3f}, SRMR = {s['srmr']:.3f}. Table 3 and Figure 1 give the estimates.")
lab = {"PCA~GUI": ("H1", "GUI → PCA"), "CGz~GUI": ("H2", "GUI → CG"), "UR~GUI": ("H3", "GUI → UR"), "VER~GUI": ("H4", "GUI → VER"), "IDQ~PCA": ("H5", "PCA → IDQ"), "IDQ~CGz": ("H6", "CG → IDQ"), "IDQ~UR": ("H7", "UR → IDQ"), "IDQ~VER": ("H8", "VER → IDQ"), "PCA~INTF": ("H10a", "GUI × FK → PCA"), "CGz~INTF": ("H10b", "GUI × FK → CG"), "UR~INTA": ("H11a", "GUI × AIL → UR"), "VER~INTA": ("H11b", "GUI × AIL → VER"), "IDQ~GUI": ("—", "GUI → IDQ (direct)"), "IDQ~FKz": ("—", "FK → IDQ"), "IDQ~AIL": ("—", "AIL → IDQ")}
rows = [(h, t, m(PA[k]["b"]), f"{PA[k]['se']:.2f}", m(PA[k]["beta"]), pv(PA[k]["p"]).replace("p ", "").replace("= ", "") if PA[k]["p"] >= .001 else "< .001", "Supported" if H.get(h) else "—") for k, (h, t) in lab.items()]
d.table("Table 3. Structural estimates", ["Hyp.", "Path", "b", "SE", "β", "p", "Result"], rows, widths=[800, 2700, 900, 800, 900, 1000, 1500])
d.para(f"GenAI use predicted higher perceived competence ({bz('PCA~GUI')}; H1) and a larger calibration gap ({bz('CGz~GUI')}; H2), more uncritical reliance ({bz('UR~GUI')}; H3) and more verification ({bz('VER~GUI')}; H4). Decision quality was lower when perceived competence ({bz('IDQ~PCA')}; H5), the calibration gap ({bz('IDQ~CGz')}; H6) or uncritical reliance ({bz('IDQ~UR')}; H7) was higher, and higher with verification ({bz('IDQ~VER')}; H8). The direct effect of use on quality was small ({bz('IDQ~GUI')}), consistent with full mediation. Explained variance was R² = {R['r2']['PCA']:.2f} (PCA), {R['r2']['CGz']:.2f} (CG), {R['r2']['UR']:.2f} (UR), {R['r2']['VER']:.2f} (VER) and {R['r2']['IDQ']:.2f} (IDQ).")
d.para(f"Moderation. Financial knowledge weakened the effect of use on perceived competence ({bz('PCA~INTF')}; H10a) and on the calibration gap ({bz('CGz~INTF')}; H10b). AI literacy weakened the effect of use on uncritical reliance ({bz('UR~INTA')}; H11a) and strengthened its effect on verification ({bz('VER~INTA')}; H11b). Interaction effect sizes were small to moderate (f² = {R['f2_int']['PCA']:.3f} for PCA, {R['f2_int']['CGz']:.3f} for CG, {R['f2_int']['UR']:.3f} for UR, {R['f2_int']['VER']:.3f} for VER), typical of interaction effects in non-experimental data.")
d.heading("4.4 Indirect and conditional indirect effects", 2)
rows = []
for lbl, k in [("Via PCA", "ind_PCA"), ("Via CG", "ind_CG"), ("Via UR", "ind_UR"), ("Via VER", "ind_VER")]:
    rows.append((lbl, ci(k + "_low"), ci(k + "_mean"), ci(k + "_high")))
rows.append(("Illusion route (PCA + CG)", ci("ind_illusion_low"), ci("ind_illusion_mean"), ci("ind_illusion_high")))
d.table("Table 4. Conditional indirect effects of GenAI use on decision quality (unstandardized; 95% bootstrap CI)", ["Route", "Moderator −1 SD", "Mean", "+1 SD"], rows, widths=[2500, 2300, 2300, 2300],
        note="For the PCA and CG routes the moderator is financial knowledge; for the UR and VER routes it is AI literacy. Intervals are percentile bootstrap, B = " + str(R["boot_n"]) + ".")
d.para(f"At mean moderator levels the indirect effects were {ci('ind_PCA_mean')} via perceived competence, {ci('ind_CG_mean')} via the calibration gap, {ci('ind_UR_mean')} via uncritical reliance, and {ci('ind_VER_mean')} via verification, supporting H9. The negative illusion route was larger at low than at high knowledge (−1 SD: {ci('ind_illusion_low')}; +1 SD: {ci('ind_illusion_high')}), and the verification route was larger at high AI literacy ({ci('ind_VER_high')}) than at low ({ci('ind_VER_low')}). Indices of moderated mediation were {ci('imm_PCA')} (PCA), {ci('imm_CG')} (CG), {ci('imm_UR')} (UR) and {ci('imm_VER')} (VER). The total indirect effect was {ci('total_ind_mean')}, so the opposing routes largely offset one another; the total effect (direct + indirect) was {ci('total_mean')}.")
d.heading("4.5 Competing models", 2)
rows = [(k, v["name"], f"{v['chi2']:.0f}", f"{v['df']:.0f}", f"{v['cfi']:.3f}", f"{v['rmsea']:.3f}", f"{v['aic']:.0f}", f"{v['bic']:.0f}") for k, v in R["models"].items()]
d.table("Table 5. Competing structural models", ["Model", "Specification", "χ²", "df", "CFI", "RMSEA", "AIC", "BIC"], rows, widths=[600, 3500, 700, 600, 700, 800, 800, 800], size=18)
d.para("The hypothesised model M1 had the lowest BIC and the best fit among the five structures; removing moderation (M2), omitting either the illusion or the reliance/verification mediators (M3, M4) or removing all mediators (M5) worsened fit. Values of AIC and BIC from semopy are reported for relative comparison only.")
d.heading("4.6 Robustness checks", 2)
def rob(dct, keys):
    return ", ".join(f"{k.split('~')[1].replace('CGz','CG')}: β = {m(dct[k]['beta'])}" for k in keys)
rk = ["PCA~GUI", "CGz~GUI", "UR~GUI", "VER~GUI", "IDQ~PCA", "IDQ~CGz", "IDQ~UR", "IDQ~VER"]
rows = []
for k in rk:
    rows.append((lab[k][1], m(PA[k]["beta"]), m(R["dwls"][k]["beta"]) if R.get("dwls") else "–", m(R["resid_centered"][k]["beta"]), m(R["respec"]["paths"][k]["beta"]), m(R["trimmed"][k]["beta"]), m(R["users_only"][k]["beta"]) if R.get("users_only") else "–"))
d.table("Table 6. Robustness of key standardized paths", ["Path", "Baseline", "DWLS (no interactions)", "Residual-centred", "Respecified", "Trimmed 5%", "Regular users"], rows, widths=[1700, 1000, 1400, 1300, 1200, 1100, 1300], size=18)
d.para(f"Estimates were stable in sign and size across estimators (DWLS for ordinal indicators, ignoring interaction terms), a residual-centred product-indicator specification (CFI = {R['resid_centered_fit']['cfi']:.3f}), a specification adding the four largest within-factor residual correlations ({', '.join(a + '–' + b for a, b in R['respec']['pairs'])}; CFI = {R['respec']['fit']['cfi']:.3f}), removal of the {R['outliers_removed']} most extreme multivariate cases, and restriction to the {R['users_n']} regular users (GUI1 ≥ 3).")
d.heading("4.7 Behavioural criterion validity", 2)
v = R["vignette"]
d.para(f"As an external check that does not share response format with the scales, respondents judged four AI statements about valuation and accounting, two of them wrong (Appendix A, V1–V4). The number of wrong statements accepted was predicted positively by uncritical reliance ({bz('VIGERR~UR', v)}) and negatively by verification ({bz('VIGERR~VER', v)}), controlling for use ({bz('VIGERR~GUI', v)}). This shows that the self-reported reliance and verification factors map onto observable acceptance of incorrect advice.")
# ------------------------------------------------------------------ 5 discussion
d.heading("5. Discussion")
d.para("The synthetic results illustrate the pattern the theory predicts and the design is built to detect: GenAI use raises feelings of competence and overestimation, and raises uncritical reliance, each of which is linked to poorer decision quality; at the same time heavier users also verify more, and verification is the strongest positive correlate of quality. The net association between use and quality is therefore small, which would be mistaken for “no effect” in a simple regression but hides two opposing behavioural channels. If the pattern replicates on real data, it implies that the question “does GenAI help investors?” should be replaced by “which uses, by whom, with which checking habits?”")
d.para("Both competences operate as boundary conditions in the predicted directions. Objective knowledge buffers the inflation of confidence—consistent with the metacognitive account in which the same knowledge that produces competence also allows its limits to be recognised (Kruger & Dunning, 1999; Ehrlinger et al., 2008)—while AI literacy changes the //kind// of reliance rather than its quantity: literate users do not use AI less, they check it more. This is consistent with calibrated-trust accounts (Lee & See, 2004) and suggests that training that targets verification routines may matter more than warnings alone.")
d.para("//Practical implications.// For investor-education bodies, brokers and regulators, the findings (if replicated) imply (i) pairing GenAI features in investment apps with prompts to verify against official filings, (ii) offering calibration feedback (predict-then-test exercises), and (iii) targeting AI literacy content at heavy users with low objective knowledge, who show the largest conditional illusion effect. For auditors and accounting educators, items on audit opinions, cash-flow versus profit and ratio calculation can serve as a diagnostic of knowledge against which confidence is benchmarked.")
d.heading("6. Limitations and future research")
d.para("First and foremost, the data are synthetic; the coefficients demonstrate the pipeline, not a finding. Second, with real data the design remains cross-sectional and self-reported, so causal ordering (use → illusion) cannot be established; overconfident investors may also self-select into heavy use. Panel data, or an experiment that randomises exposure to correct versus incorrect AI advice and AI-label versus analyst-label (Dietvorst et al., 2015; Logg et al., 2019), would identify causal effects. Third, the calibration gap is based on an eight-item test and a single prediction; richer tests, over-placement (percentile rank) and over-precision (confidence intervals) should be added. Fourth, decision quality is self-reported; trading records (turnover, returns, disposition effect) would give behavioural outcomes. Fifth, the interaction effects are small, and latent-interaction estimates are sensitive to the product-indicator strategy; we therefore report two strategies. Sixth, scales are new or adapted and need the validation protocol (content validity, pilot, CFA, invariance across countries and languages) before inferential use. Finally, generalisability to markets with different disclosure regimes and AI access remains open.")
d.heading("7. Conclusion")
d.para("Generative AI can make investors feel more competent faster than it makes them more competent. The design proposed here separates illusion, uncritical reliance and verification, and tests the two competences—objective knowledge and AI literacy—that should make GenAI use safe. The synthetic demonstration shows the model is identified, estimable and interpretable; the decisive test is a real, pre-registered survey.")
d.heading("Declarations")
d.para("**Data and code availability.** Synthetic dataset (CSV/XLSX), the Python script (paper3_analysis.py, with simlib.py) and the Colab notebook are provided with this manuscript. **Ethics.** For real data collection, ethics approval and informed consent are required; the present synthetic data involve no human participants. **Funding / conflicts of interest.** [to be completed]. **AI-assistance disclosure.** AI tools were used to draft code and text; the authors are responsible for the content and must verify all references and DOIs against Crossref before submission.", indent=False)
d.heading("References")
txt = d.parts  # (only for completeness)
cited = {k for k in P.REF}
# only references actually cited in text: match on first author surname + year
body = " ".join(re.sub(r"<[^>]+>", "", p) for p in d.parts)
def used(k):
    r = P.REF[k]; a = re.match(r"([^,]+),", r).group(1); y = re.search(r"\((\d{4})\)", r).group(1)
    return (a in body and y in body) and (f"{a}" in body)
refs = sorted([k for k in P.REF if used(k)], key=lambda k: P.REF[k].lower())
for k in refs: d.reference(P.REF[k])
print("refs listed:", len(refs), "of", len(P.REF))
# ------------------------------------------------------------------ appendix
d.page_break(); d.heading("Appendix A. Instrument, origin of each scale and standardized loadings")
d.para("Origin: **R-B** = research-based (adapted); **R-M** = researcher-made, theory-derived; **Mixed** = both. Loadings are from the measurement model (Table 2 of the replication files). The full questionnaire with all references per variable, scoring and a Persian version are provided separately.", indent=False)
for var in P.VARS:
    rows = []
    for c_, e, _ in var["items"]:
        rows.append((c_, e, m(R["loadings"][c_]) if c_ in R["loadings"] else "–"))
    short = {P.RB: "R-B", P.RM: "R-M", P.MIX: "Mixed"}[var["cls"]]
    d.table(f"{var['name']} ({var['code']}) – origin: {short}; sources: {', '.join(re.match(r'([^,]+),', P.REF[k]).group(1) for k in var['refs'])}", ["Code", "Item", "λ"], rows, widths=[800, 7500, 800], size=18)
d.save(os.path.join(OUT, "Paper3_Manuscript_EN.docx"), title=TITLE)
print("saved")
