# -*- coding: utf-8 -*-
"""Paper 3 instrument: items (EN + FA), response formats, origin classification and references per variable."""

RB = "Research-based (adapted)"          # پژوهش‌محور (اقتباس‌شده)
RM = "Researcher-made (theory-derived)"  # محقق‌ساخته (برگرفته از نظریه)
MIX = "Mixed: adapted + researcher-made"

REF = {  # key -> APA 7 (DOIs must be verified against Crossref before submission)
 "kruger1999": "Kruger, J., & Dunning, D. (1999). Unskilled and unaware of it: How difficulties in recognizing one's own incompetence lead to inflated self-assessments. //Journal of Personality and Social Psychology, 77//(6), 1121–1134. https://doi.org/10.1037/0022-3514.77.6.1121",
 "moore2008": "Moore, D. A., & Healy, P. J. (2008). The trouble with overconfidence. //Psychological Review, 115//(2), 502–517. https://doi.org/10.1037/0033-295X.115.2.502",
 "ehrlinger2008": "Ehrlinger, J., Johnson, K., Banner, M., Dunning, D., & Kruger, J. (2008). Why the unskilled are unaware: Further explorations of (absent) self-insight among the incompetent. //Organizational Behavior and Human Decision Processes, 105//(1), 98–121. https://doi.org/10.1016/j.obhdp.2007.05.002",
 "parasuraman2010": "Parasuraman, R., & Manzey, D. H. (2010). Complacency and bias in human use of automation: An attentional integration. //Human Factors, 52//(3), 381–410. https://doi.org/10.1177/0018720810376055",
 "goddard2012": "Goddard, K., Roudsari, A., & Wyatt, J. C. (2012). Automation bias: A systematic review of frequency, effect mediators, and mitigators. //Journal of the American Medical Informatics Association, 19//(1), 121–127. https://doi.org/10.1136/amiajnl-2011-000089",
 "skitka1999": "Skitka, L. J., Mosier, K. L., & Burdick, M. (1999). Does automation bias decision-making? //International Journal of Human-Computer Studies, 51//(5), 991–1006. https://doi.org/10.1006/ijhc.1999.0252",
 "lee2004": "Lee, J. D., & See, K. A. (2004). Trust in automation: Designing for appropriate reliance. //Human Factors, 46//(1), 50–80. https://doi.org/10.1518/hfes.46.1.50_30392",
 "hoff2015": "Hoff, K. A., & Bashir, M. (2015). Trust in automation: Integrating empirical evidence on factors that influence trust. //Human Factors, 57//(3), 407–434. https://doi.org/10.1177/0018720814547570",
 "jian2000": "Jian, J.-Y., Bisantz, A. M., & Drury, C. G. (2000). Foundations for an empirically determined scale of trust in automated systems. //International Journal of Cognitive Ergonomics, 4//(1), 53–71. https://doi.org/10.1207/S15327566IJCE0401_04",
 "dietvorst2015": "Dietvorst, B. J., Simmons, J. P., & Massey, C. (2015). Algorithm aversion: People erroneously avoid algorithms after seeing them err. //Journal of Experimental Psychology: General, 144//(1), 114–126. https://doi.org/10.1037/xge0000033",
 "logg2019": "Logg, J. M., Minson, J. A., & Moore, D. A. (2019). Algorithm appreciation: People prefer algorithmic to human judgment. //Organizational Behavior and Human Decision Processes, 151//, 90–103. https://doi.org/10.1016/j.obhdp.2018.12.005",
 "wang2023": "Wang, B., Rau, P.-L. P., & Yuan, T. (2023). Measuring user competence in using artificial intelligence: Validity and reliability of artificial intelligence literacy scale. //Behaviour & Information Technology, 42//(9), 1324–1337. https://doi.org/10.1080/0144929X.2022.2072768",
 "ng2021": "Ng, D. T. K., Leung, J. K. L., Chu, S. K. W., & Qiao, M. S. (2021). Conceptualizing AI literacy: An exploratory review. //Computers and Education: Artificial Intelligence, 2//, 100041. https://doi.org/10.1016/j.caeai.2021.100041",
 "long2020": "Long, D., & Magerko, B. (2020). What is AI literacy? Competencies and design considerations. //Proceedings of the 2020 CHI Conference on Human Factors in Computing Systems// (pp. 1–16). ACM. https://doi.org/10.1145/3313831.3376727",
 "lusardi2014": "Lusardi, A., & Mitchell, O. S. (2014). The economic importance of financial literacy: Theory and evidence. //Journal of Economic Literature, 52//(1), 5–44. https://doi.org/10.1257/jel.52.1.5",
 "vanrooij2011": "Van Rooij, M., Lusardi, A., & Alessie, R. (2011). Financial literacy and stock market participation. //Journal of Financial Economics, 101//(2), 449–472. https://doi.org/10.1016/j.jfineco.2011.03.006",
 "parker2005": "Parker, A. M., & Fischhoff, B. (2005). Decision-making competence: External validation through an individual-differences approach. //Journal of Behavioral Decision Making, 18//(1), 1–27. https://doi.org/10.1002/bdm.481",
 "bruine2007": "Bruine de Bruin, W., Parker, A. M., & Fischhoff, B. (2007). Individual differences in adult decision-making competence. //Journal of Personality and Social Psychology, 92//(5), 938–956. https://doi.org/10.1037/0022-3514.92.5.938",
 "venkatesh2012": "Venkatesh, V., Thong, J. Y. L., & Xu, X. (2012). Consumer acceptance and use of information technology: Extending the unified theory of acceptance and use of technology. //MIS Quarterly, 36//(1), 157–178. https://doi.org/10.2307/41410412",
 "barber2001": "Barber, B. M., & Odean, T. (2001). Boys will be boys: Gender, overconfidence, and common stock investment. //The Quarterly Journal of Economics, 116//(1), 261–292. https://doi.org/10.1162/003355301556400",
 "barber2000": "Barber, B. M., & Odean, T. (2000). Trading is hazardous to your wealth: The common stock investment performance of individual investors. //The Journal of Finance, 55//(2), 773–806. https://doi.org/10.1111/0022-1082.00226",
 "grinblatt2009": "Grinblatt, M., & Keloharju, M. (2009). Sensation seeking, overconfidence, and trading activity. //The Journal of Finance, 64//(2), 549–578. https://doi.org/10.1111/j.1540-6261.2009.01443.x",
 "glaser2007": "Glaser, M., & Weber, M. (2007). Overconfidence and trading volume. //The Geneva Risk and Insurance Review, 32//(1), 1–36. https://doi.org/10.1007/s10713-007-0003-3",
 "dacunto2019": "D'Acunto, F., Prabhala, N., & Rossi, A. G. (2019). The promises and pitfalls of robo-advising. //The Review of Financial Studies, 32//(5), 1983–2020. https://doi.org/10.1093/rfs/hhz014",
 "ji2023": "Ji, Z., Lee, N., Frieske, R., Yu, T., Su, D., Xu, Y., Ishii, E., Bang, Y. J., Madotto, A., & Fung, P. (2023). Survey of hallucination in natural language generation. //ACM Computing Surveys, 55//(12), Article 248. https://doi.org/10.1145/3571730",
 "lopezlira2023": "Lopez-Lira, A., & Tang, Y. (2023). Can ChatGPT forecast stock price movements? Return predictability and large language models. //SSRN Working Paper//. https://doi.org/10.2139/ssrn.4412788",
 "messeri2024": "Messeri, L., & Crockett, M. J. (2024). Artificial intelligence and illusions of understanding in scientific research. //Nature, 627//(8002), 49–58. https://doi.org/10.1038/s41586-024-07146-0",
 "pennycook2019": "Pennycook, G., & Rand, D. G. (2019). Lazy, not biased: Susceptibility to partisan fake news is better explained by lack of reasoning than by motivated reasoning. //Cognition, 188//, 39–50. https://doi.org/10.1016/j.cognition.2018.06.011",
 "lawshe1975": "Lawshe, C. H. (1975). A quantitative approach to content validity. //Personnel Psychology, 28//(4), 563–575. https://doi.org/10.1111/j.1744-6570.1975.tb01393.x",
 "polit2006": "Polit, D. F., & Beck, C. T. (2006). The content validity index: Are you sure you know what's being reported? Critique and recommendations. //Research in Nursing & Health, 29//(5), 489–497. https://doi.org/10.1002/nur.20147",
 "boateng2018": "Boateng, G. O., Neilands, T. B., Frongillo, E. A., Melgar-Quiñonez, H. R., & Young, S. L. (2018). Best practices for developing and validating scales for health, social, and behavioral research: A primer. //Frontiers in Public Health, 6//, Article 149. https://doi.org/10.3389/fpubh.2018.00149",
 "brislin1970": "Brislin, R. W. (1970). Back-translation for cross-cultural research. //Journal of Cross-Cultural Psychology, 1//(3), 185–216. https://doi.org/10.1177/135910457000100301",
 "podsakoff2003": "Podsakoff, P. M., MacKenzie, S. B., Lee, J.-Y., & Podsakoff, N. P. (2003). Common method biases in behavioral research: A critical review of the literature and recommended remedies. //Journal of Applied Psychology, 88//(5), 879–903. https://doi.org/10.1037/0021-9010.88.5.879",
 "hu1999": "Hu, L., & Bentler, P. M. (1999). Cutoff criteria for fit indexes in covariance structure analysis: Conventional criteria versus new alternatives. //Structural Equation Modeling, 6//(1), 1–55. https://doi.org/10.1080/10705519909540118",
 "fornell1981": "Fornell, C., & Larcker, D. F. (1981). Evaluating structural equation models with unobservable variables and measurement error. //Journal of Marketing Research, 18//(1), 39–50. https://doi.org/10.1177/002224378101800104",
 "henseler2015": "Henseler, J., Ringle, C. M., & Sarstedt, M. (2015). A new criterion for assessing discriminant validity in variance-based structural equation modeling. //Journal of the Academy of Marketing Science, 43//(1), 115–135. https://doi.org/10.1007/s11747-014-0403-8",
 "marsh2004": "Marsh, H. W., Wen, Z., & Hau, K.-T. (2004). Structural equation models of latent interactions: Evaluation of alternative estimation strategies and indicator construction. //Psychological Methods, 9//(3), 275–300. https://doi.org/10.1037/1082-989X.9.3.275",
 "little2006": "Little, T. D., Bovaird, J. A., & Widaman, K. F. (2006). On the merits of orthogonalizing powered and product terms: Implications for modeling interactions among latent variables. //Structural Equation Modeling, 13//(4), 497–519. https://doi.org/10.1207/s15328007sem1304_1",
 "preacher2008": "Preacher, K. J., & Hayes, A. F. (2008). Asymptotic and resampling strategies for assessing and comparing indirect effects in multiple mediator models. //Behavior Research Methods, 40//(3), 879–891. https://doi.org/10.3758/BRM.40.3.879",
 "hayes2015": "Hayes, A. F. (2015). An index and test of linear moderated mediation. //Multivariate Behavioral Research, 50//(1), 1–22. https://doi.org/10.1080/00273171.2014.962683",
 "maccallum1996": "MacCallum, R. C., Browne, M. W., & Sugawara, H. M. (1996). Power analysis and determination of sample size for covariance structure modeling. //Psychological Methods, 1//(2), 130–149. https://doi.org/10.1037/1082-989X.1.2.130",
 "igolkina2020": "Igolkina, A. A., & Meshcheryakov, G. (2020). semopy: A Python package for structural equation modeling. //Structural Equation Modeling, 27//(6), 952–963. https://doi.org/10.1080/10705511.2019.1704289",
 "nadeau2003": "Nadeau, C., & Bengio, Y. (2003). Inference for the generalization error. //Machine Learning, 52//(3), 239–281. https://doi.org/10.1023/A:1024068626366",
}

# ----- items: (code, English, Persian)
LIK5_AGREE = "1 = strongly disagree … 5 = strongly agree"
LIK5_FREQ = "1 = never … 5 = always"

VARS = [
 dict(code="GUI", name="Generative-AI use for investing", fa="استفادهٔ سرمایه‌گذاری از هوش مصنوعی مولد", cls=RM, scale=LIK5_FREQ, role="Exogenous latent (reflective)",
  items=[("GUI1","I use generative-AI tools (e.g., ChatGPT, Gemini, Copilot, DeepSeek) to analyse stocks or other investment options.","برای تحلیل سهام یا گزینه‌های سرمایه‌گذاری از ابزارهای هوش مصنوعی مولد (مانند ChatGPT، Gemini، Copilot، DeepSeek) استفاده می‌کنم."),
         ("GUI2","Generative AI supplies a substantial share of the information I need for my investment decisions.","هوش مصنوعی مولد بخش قابل‌توجهی از اطلاعاتی را که برای تصمیم‌های سرمایه‌گذاری لازم دارم فراهم می‌کند."),
         ("GUI3","Before buying or selling a stock I usually ask a generative-AI tool for its view.","پیش از خرید یا فروش یک سهم معمولاً نظر یک ابزار هوش مصنوعی مولد را می‌پرسم."),
         ("GUI4","Using generative AI has become part of my routine investment analysis.","استفاده از هوش مصنوعی مولد بخشی از روال تحلیل سرمایه‌گذاری من شده است.")],
  refs=["venkatesh2012"], why="No validated scale exists for investor use of generative AI. Items were written by the authors; only the frequency/intensity format follows the use-behaviour logic of UTAUT2 (Venkatesh et al., 2012). Status: researcher-made, to be validated (CVR/CVI, pilot, EFA/CFA)."),
 dict(code="FK", name="Objective financial/accounting knowledge test (8 items, scored 0/1)", fa="آزمون عینی دانش مالی ـ حسابداری (۸ سؤال)", cls=MIX, scale="Multiple choice / true–false–don't know; correct = 1", role="Latent 'knowledge' (KR-20) – the moderator is modelled through the standardized test score",
  items=[("FK1","Your deposit earns 20% per year and inflation is 35% per year. After one year, the purchasing power of the deposit will: (a) increase (b) decrease* (c) stay the same (d) don't know","سود سپرده ۲۰٪ و تورم ۳۵٪ سالانه است. پس از یک سال قدرت خرید سپرده: الف) بیشتر می‌شود ب) کمتر می‌شود* ج) ثابت می‌ماند د) نمی‌دانم"),
         ("FK2","'Buying the shares of a single company is usually less risky than buying a diversified fund.' True / False* / Don't know","«خرید سهام یک شرکت معمولاً ریسک کمتری از خرید سبد متنوع دارد.» درست / نادرست* / نمی‌دانم"),
         ("FK3","Share price 2,000 and earnings per share 200. The P/E ratio is: (a) 0.1 (b) 10* (c) 20 (d) 400,000","قیمت سهم ۲٬۰۰۰ و سود هر سهم ۲۰۰ است. P/E برابر است با: الف) ۰٫۱ ب) ۱۰* ج) ۲۰ د) ۴۰۰٬۰۰۰"),
         ("FK4","Net income 500 bn and 500 m shares outstanding. EPS is: (a) 1 (b) 100 (c) 1,000* (d) 10,000 (currency units)","سود خالص ۵۰۰ میلیارد و ۵۰۰ میلیون سهم. EPS برابر است با: الف) ۱ ب) ۱۰۰ ج) ۱٬۰۰۰* د) ۱۰٬۰۰۰"),
         ("FK5","'Accounting profit always equals operating cash flow.' True / False* ","«سود حسابداری همیشه برابر جریان نقد عملیاتی است.» درست / نادرست*"),
         ("FK6","'An unqualified audit opinion guarantees the firm's future profitability.' True / False*","«اظهارنظر مقبول حسابرس تضمین‌کنندهٔ سودآوری آیندهٔ شرکت است.» درست / نادرست*"),
         ("FK7","'An investment with a higher expected return usually carries higher risk.' True* / False","«سرمایه‌گذاری با بازده مورد انتظار بالاتر معمولاً ریسک بیشتری دارد.» درست* / نادرست"),
         ("FK8","100 m invested at a fixed 10% p.a. grows after two years to: (a) 110 (b) 120 (c) 121* (d) 100","۱۰۰ میلیون با بازده ثابت ۱۰٪ سالانه پس از دو سال می‌شود: الف) ۱۱۰ ب) ۱۲۰ ج) ۱۲۱* د) ۱۰۰")],
  refs=["lusardi2014", "vanrooij2011"], why="FK1, FK2, FK7, FK8 follow the logic of the 'Big Three' / OECD-style questions (inflation, risk diversification, compounding) of Lusardi & Mitchell (2014) and Van Rooij et al. (2011), rewritten with local numbers; FK3–FK6 (P/E, EPS, cash-flow vs. profit, audit opinion) are researcher-made accounting items. Status: partly research-based, partly researcher-made."),
 dict(code="CG", name="Calibration gap (overestimation): predicted minus actual test score", fa="شکاف کالیبراسیون (بیش‌برآورد): نمرهٔ پیش‌بینی‌شده منهای نمرهٔ واقعی", cls=RB, scale="C1: 0–8 integer; C2: rank 1–100", role="Behavioural/performance-based indicator (not a Likert scale)",
  items=[("C1","How many of the 8 questions above do you think you answered correctly? (0–8)","فکر می‌کنید از ۸ سؤال بالا چند سؤال را درست پاسخ داده‌اید؟ (۰ تا ۸)"),
         ("C2","Compared with 100 other active investors, what is your rank in financial knowledge? (1 = lowest, 100 = highest)","در مقایسه با ۱۰۰ سرمایه‌گذار فعال دیگر، رتبهٔ خود را از نظر دانش مالی چند می‌دانید؟ (۱ = پایین‌ترین، ۱۰۰ = بالاترین)")],
  refs=["kruger1999", "moore2008", "ehrlinger2008"], why="Method-based: the calibration/over-placement logic of Kruger & Dunning (1999) and Moore & Healy (2008) is applied directly (CG = C1 − actual score; CP = C2 − actual rank). The questions themselves are generic. Status: research-based method."),
 dict(code="PCA", name="Perceived competence with AI (the 'illusion' facet)", fa="شایستگی ادراک‌شده با کمک هوش مصنوعی", cls=RM, scale=LIK5_AGREE, role="Mediator (reflective latent)",
  items=[("PCA1","With the help of AI, my analysis of the stock market is better than that of most other investors.","با کمک هوش مصنوعی، تحلیل من از بازار سهام از اغلب سرمایه‌گذاران دیگر بهتر است."),
         ("PCA2","With AI, I am confident that my price-trend forecasts will turn out correct.","با هوش مصنوعی مطمئنم پیش‌بینی‌هایم دربارهٔ روند قیمت درست از آب درمی‌آید."),
         ("PCA3","With AI, I feel I understand financial statements better than before.","با هوش مصنوعی احساس می‌کنم صورت‌های مالی را بهتر از قبل می‌فهمم."),
         ("PCA4","With AI, I no longer need much help from a financial professional.","با هوش مصنوعی دیگر به کمک زیاد متخصص مالی نیاز ندارم.")],
  refs=["moore2008", "barber2001", "grinblatt2009", "glaser2007"], why="Overconfidence/perceived-ability constructs are established (Barber & Odean, 2001; Glaser & Weber, 2007; Grinblatt & Keloharju, 2009), but no scale targets AI-assisted competence; the four items are new wordings of better-than-average, forecast-confidence and self-sufficiency facets. Status: researcher-made, theory-derived."),
 dict(code="UR", name="Uncritical reliance on AI output (automation-bias tendency)", fa="تکیهٔ بی‌چون‌وچرا بر خروجی هوش مصنوعی", cls=RM, scale=LIK5_AGREE, role="Mediator (reflective latent)",
  items=[("UR1","I usually accept an AI answer without checking it again.","معمولاً پاسخ هوش مصنوعی را بدون بررسی دوباره می‌پذیرم."),
         ("UR2","If the AI's view differs from my own analysis, I tend to trust the AI.","اگر نظر هوش مصنوعی با تحلیل خودم فرق کند، به هوش مصنوعی اعتماد می‌کنم."),
         ("UR3","Because AI summarises for me, I read financial statements directly less often.","چون هوش مصنوعی خلاصه می‌کند، کمتر صورت‌های مالی را مستقیم می‌خوانم."),
         ("UR4","I find fluent, confident AI answers more correct than hesitant ones.","پاسخ‌های روان و قاطع هوش مصنوعی را درست‌تر از پاسخ‌های مردد می‌دانم.")],
  refs=["parasuraman2010", "goddard2012", "skitka1999", "lee2004", "jian2000", "dietvorst2015", "logg2019"], why="Automation bias/complacency is defined by Parasuraman & Manzey (2010), Goddard et al. (2012) and Skitka et al. (1999); the trust-scale tradition (Jian et al., 2000) offers wording ideas only. Items are original, investment-specific. Status: researcher-made, theory-derived."),
 dict(code="VER", name="Verification behaviour (calibrated reliance)", fa="رفتار راستی‌آزمایی", cls=RM, scale=LIK5_FREQ, role="Mediator (reflective latent)",
  items=[("VER1","I compare numbers and claims from AI with official filings or financial statements.","عددها و ادعاهای هوش مصنوعی را با گزارش‌های رسمی (کدال) یا صورت‌های مالی مقایسه می‌کنم."),
         ("VER2","I confirm AI answers with at least one independent source.","پاسخ هوش مصنوعی را با دست‌کم یک منبع مستقل دیگر تأیید می‌کنم."),
         ("VER3","I ask the tool for its sources and actually check them.","از ابزار منبع می‌خواهم و منبع را واقعاً بررسی می‌کنم."),
         ("VER4","I redo important calculations myself.","محاسبات مهم را خودم دوباره انجام می‌دهم.")],
  refs=["lee2004", "hoff2015", "pennycook2019", "ji2023"], why="Verification as the behavioural counterpart of appropriate (calibrated) reliance follows Lee & See (2004) and Hoff & Bashir (2015); the need for it follows from hallucination evidence (Ji et al., 2023). Items are original. Status: researcher-made, theory-derived."),
 dict(code="AIL", name="AI literacy", fa="سواد هوش مصنوعی", cls=RB, scale=LIK5_AGREE, role="Moderator (reflective latent)",
  items=[("AIL1","I know that generative AI can produce wrong but convincing information.","می‌دانم هوش مصنوعی مولد ممکن است اطلاعات نادرست اما قانع‌کننده تولید کند."),
         ("AIL2","I know these tools are trained on dated data and may be unaware of current market information.","می‌دانم این ابزارها با داده‌های تاریخ‌دار آموزش دیده‌اند و ممکن است از اطلاعات به‌روز بازار بی‌خبر باشند."),
         ("AIL3","I can phrase a question so that I get a more accurate answer.","می‌توانم پرسش را طوری بنویسم که پاسخ دقیق‌تری بگیرم."),
         ("AIL4","I can evaluate the quality of an AI tool's answer.","می‌توانم کیفیت پاسخ یک ابزار هوش مصنوعی را ارزیابی کنم."),
         ("AIL5","I know AI may be biased or use incomplete information.","می‌دانم هوش مصنوعی ممکن است سوگیری داشته باشد یا از اطلاعات ناقص استفاده کند."),
         ("AIL6","I know when I should not rely on AI for a financial decision.","می‌دانم چه زمانی نباید برای یک تصمیم مالی به هوش مصنوعی تکیه کنم.")],
  refs=["wang2023", "ng2021", "long2020"], why="Competency domains (awareness, use, evaluation, ethics/limits) follow Wang et al. (2023), Ng et al. (2021) and Long & Magerko (2020); items are paraphrased and re-contextualised to investing, so the original validation does not transfer automatically. Status: research-based (adapted); re-validate in the target population."),
 dict(code="IDQ", name="Investment decision quality", fa="کیفیت تصمیم سرمایه‌گذاری", cls=MIX, scale=LIK5_AGREE, role="Outcome (reflective latent)",
  items=[("IDQ1","My investment decisions are usually based on documented analysis.","تصمیم‌های سرمایه‌گذاری من معمولاً بر تحلیل مستند استوارند."),
         ("IDQ2","I am satisfied with the outcome of my investment decisions over the past year.","از نتیجهٔ تصمیم‌های سرمایه‌گذاری خود در یک سال گذشته رضایت دارم."),
         ("IDQ3","My portfolio return over the past year matched my expectations.","بازده سبد من در یک سال گذشته مطابق انتظارم بوده است."),
         ("IDQ4","My decisions are aligned with my long-term financial goals.","تصمیم‌های من با اهداف مالی بلندمدتم هم‌راستا هستند."),
         ("IDQ5","I rarely regret my trading decisions.","به‌ندرت از تصمیم‌های معاملاتی خود پشیمان می‌شوم.")],
  refs=["parker2005", "bruine2007"], why="Decision competence is conceptualised after Parker & Fischhoff (2005) and Bruine de Bruin et al. (2007), whose instrument measures general decision skills with tasks, not self-report; the five self-report items on process, outcome, goal-fit and regret were written by the authors. Status: researcher-made, theory-derived (shared with Papers 1–2)."),
 dict(code="VIG", name="Vignette task: acceptance of incorrect AI advice (behavioural criterion)", fa="وینیت‌های توصیهٔ نادرست هوش مصنوعی (معیار رفتاری)", cls=RM, scale="Accept / verify first / reject", role="Criterion measure (VIGERR = number of wrong AI answers accepted, 0–2)",
  items=[("V1","AI says: 'Firm A has price 1,000 and EPS 200, so P/E = 20 — it is cheap.' (incorrect: P/E = 5)","هوش مصنوعی: «شرکت الف با قیمت ۱٬۰۰۰ و EPS برابر ۲۰۰، P/E برابر ۲۰ دارد؛ پس ارزان است.» (نادرست: P/E = ۵)"),
         ("V2","AI says: 'High accounting profit is not necessarily strong cash flow; check operating cash flow too.' (correct)","هوش مصنوعی: «سود حسابداری بالا لزوماً جریان نقد قوی نیست؛ جریان نقد عملیاتی را هم ببینید.» (درست)"),
         ("V3","AI says: 'An unqualified audit opinion means the share will rise over the next six months.' (incorrect)","هوش مصنوعی: «اظهارنظر مقبول حسابرس یعنی سهم در شش ماه آینده رشد می‌کند.» (نادرست)"),
         ("V4","AI says: 'Diversification reduces firm-specific risk but cannot remove systematic risk.' (correct)","هوش مصنوعی: «تنوع‌بخشی ریسک خاص شرکت را کم می‌کند اما ریسک سیستماتیک را حذف نمی‌کند.» (درست)")],
  refs=["dietvorst2015", "logg2019", "dacunto2019"], why="Researcher-made vignettes with a known answer key; design logic follows the advice-taking literature (Dietvorst et al., 2015; Logg et al., 2019). Status: researcher-made."),
]

DEMO = [("D1","Gender","جنسیت"),("D2","Age (years)","سن"),("D3","Education (diploma / bachelor / master / doctorate)","تحصیلات"),
        ("D4","Years of stock-trading experience","سابقهٔ معامله"),("D5","Approximate portfolio value","ارزش تقریبی سبد"),
        ("D6","Frequency of generative-AI use for investing (never … daily)","فراوانی استفاده از هوش مصنوعی مولد"),
        ("D7","Main uses (multiple choice): explaining concepts, summarising news, reading filings, fundamental analysis, technical analysis, buy/sell suggestions, calculations","کاربردها (چندگزینه‌ای)")]
VALID = ["lawshe1975", "polit2006", "boateng2018", "brislin1970", "podsakoff2003"]
